/**
 * The AI check of the claims registry: Claude Opus 5.5, prompted to act as a senior
 * GNSS/SBAS integrity engineer, checked each claim against its sources (reading the
 * public ones it could reach) and gave a verdict; a second pass re-checked every
 * correction and every unresolved claim against the primary documents. A claim with an
 * entry here shows as "Checked by AI, awaiting expert" (index.ts). This is not a
 * sign-off: "Reviewed" stays for a named, qualified reviewer. Claims the model could not
 * trace keep their status and are listed in report.ts OPEN_QUESTIONS.
 */
import type { AiCheck } from './types'

const MODEL = 'Claude Opus 5.5'
const ON = '2026-10-05'

/** `on` only when the entry was re-checked after the main pass (its text or value changed). */
type Entry = Omit<AiCheck, 'model' | 'on'> & { on?: string }
type Checked = AiCheck['checked'][number]

/** A document the check read itself. */
const read = (source: string, section?: string): Checked => ({ source, section, read: true })
/** A document the check could not read: the point rests on expertise or on what quotes it. */
const known = (source: string, section?: string): Checked => ({ source, section, read: false })

const A10 = 'ICAO Annex 10 Vol I (8th ed.)'
const D9849 = 'ICAO Doc 9849 (3rd ed., 2017)'
const D9849_5 = 'ICAO Doc 9849 (5th ed., 2025)'
const D4444 = 'ICAO Doc 4444 (16th ed., Amdt 8)'
const D9613 = 'ICAO Doc 9613 (5th ed., 2023)'
const DO229 = 'RTCA DO-229'
const ED259 = 'EUROCAE ED-259'
const SDD = 'EGNOS SoL SDD v3.6'
const ISGPS = 'IS-GPS-200N'
const SPSPS = 'GPS SPS Performance Standard (2020)'
const RTKLIB = 'RTKLIB src/sbas.c'
const WALTER = 'Walter, "WAAS MOPS: Practical Examples" (ICAO copy)'
const DRAFT = 'ICAO GSWG/5 draft amendment to Annex 10 App B'
const FASDB = 'EUROCONTROL FAS Data Block Tool help'
const GPSGOV = 'gps.gov Space Segment page (archived)'
const EWA24 = 'ESSP, EWA for SoL aviation users (March 2024)'
const NAVIPEDIA_WAAS = 'ESA Navipedia, WAAS Performances (FAA WAAS PS table)'

const ENTRIES: Readonly<Record<string, Entry>> = {
  // The claims of the SBAS worldwide page, the service-area map and the training layer (second pass, 5 October 2026).
  "world.waas": { verdict: "confirmed", rationale: "PAN #97 evaluates the WAAS signal from PRN 131 (SM9), 133 (S15) and 135 (G30), and its WRS antenna-position table lists 38 distinct site codes. The FAA worldwide sheet gives commissioning in July 2003, LP minima from January 2011 and 'Developing a Dual-frequency service - 2027'. Master/uplink counts (3/6) remain secondary-source only, as the claim note already says.", checked: [{"source": "FAA WAAS PAN Report #97 (Jul 2026)", "section": "§1 (GEOs evaluated: PRN 131, 133, 135); Table 10-1 WRS antenna positions (38 site codes counted)", "read": true}, {"source": "FAA SBAS Worldwide fact sheet (rev. 11/27/2025)", "section": "WAAS box; LP paragraph", "read": true}, {"source": "FAA WAAS Quick Facts (rev. 11/27/2025)", "section": "LPV/LP counts", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 131, 133, 135, 138", "read": true}] },
  "world.egnos": { verdict: "confirmed", rationale: "SDD 3.6 gives SDD v1.0 of 02/03/2011 (NPA, APV-I), LPV-200 declared with v3.0 on 22/09/2015, and a ground segment of 38 RIMS, two MCCs and two NLES per GEO (§3.3.2, §3.3.2.1). Service Notice #33 moved PRN 121 to operational (25 Aug 2025) and PRN 123 (ASTRA 5B, 23.5°E) to test (5 Sep 2025); MPR No. 184 (Aug 2026) reports SIS availability only for operational PRN 121 and 136.", checked: [{"source": "EGNOS SoL SDD Issue 3.6 (2024)", "section": "document history; §3.3.2, §3.3.2.1; executive summary", "read": true}, {"source": "EGNOS Service Notice #33 (Aug 2025)", "section": "GEO transition table", "read": true}, {"source": "EGNOS Monthly Performance Report No. 184 (Aug 2026)", "section": "§SIS availability; Table 7", "read": true}] },
  "world.msas": { verdict: "confirmed", rationale: "JCAB's ITF/8 IP/05 states QZS-6 (PRN 129, 90.5°E) and QZS-3 (PRN 137, 127°E) operational, QZS-7 (PRN 139) awaiting launch, LP/LPV introduced on a phased basis under LPV250 (VAL 50 m) and first LPV200 procedures planned for 2027. JCAB's 2021 paper gives MSAS V1 operations from 2007 and 13 monitor stations, 2 MCS and 3 uplink stations. The FAA sheet words the area as 'Japan and surrounding area'; 'Japan only' is the stricter reading of JCAB's paper and acceptable.", checked: [{"source": "ICAO APAC ITF/8 IP/05 (Japan, May 2026)", "section": "§1-2", "read": true}, {"source": "JCAB MSAS Status and Future Plan, ITF/3 WP/04 (Sep 2021)", "section": "system diagrams, timeline", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 129, 137, 139", "read": true}, {"source": "FAA SBAS Worldwide fact sheet (rev. 11/27/2025)", "section": "MSAS box", "read": true}] },
  "world.gagan": { verdict: "corrected", on: "2026-10-07", rationale: "Re-checked on 7 October 2026 after the text changed. The ICAO APAC SBAS implementation guidance (Attachment A to the ITF/7 report, 2025) §2.4.1 gives APV-I availability of 99% 'over 76% of the Indian land mass excluding the period of solar storms on nominal days', and §2.5 quotes e-AIP India ENR 4.3: 'APV 1: 99% of time over 76% of Indian Landmass', 'RNP 0.1: 99% of time over 100% of Indian FIR'. The claim had said APV-I over the Indian landmass; corrected to 76% of it. §2.4 says INLUS uplinks the messages 'to three geostationary communication satellites GSAT-8, GSAT-10 and GSAT-15. The GEO satellites broadcast these correction messages', so the page now shows all three as operational; ENR 4.3 makes the service 'subject to availability of at least one GAGAN GEO Satellite' and no source read says whether one is a standby, as the note says. §2.4 also gives 15 reference stations and two master control centres. The years (2013, 2015), the three INLUS and the PRNs rest on the first pass (5 October 2026): ITF/7 IP/05b §1.1-1.2 and gps.gov PRN 127, 128, 132.", checked: [{"source": "ICAO APAC Guidance Document for Implementation of SBAS (ITF/7 report Attachment A, 2025)", "section": "§2.4, §2.4.1, §2.5 (e-AIP India ENR 4.3)", "read": true}, {"source": "ICAO APAC ITF/7 IP/05b (India, May 2025)", "section": "§1.1-1.2 (first pass)", "read": true}, {"source": "AAI GAGAN System presentation (Oct 2025)", "section": "DGCA actions, way forward (first pass)", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 127, 128, 132 (first pass)", "read": true}] },
  "world.kass": { verdict: "confirmed", rationale: "ROK's ITF/8 paper states the APV-I SoL service was launched on 28 December 2023 (AIP effective 24 January 2024), the second GEO KOREASAT 6A (116°E, PRN 142) began operation on 18 February 2026 16:00 UTC, and MEASAT-3D is at 91.5°E; service 'at first in the Incheon FIR'. The FAA sheet's 'Commissioned in 2024' refers to the AIP date and does not conflict.", checked: [{"source": "ICAO APAC ITF/8 IP/07 (Republic of Korea, May 2026)", "section": "§2.1-2.4", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 134, 142", "read": true}, {"source": "FAA SBAS Worldwide fact sheet (rev. 11/27/2025)", "section": "KASS box", "read": true}] },
  "world.southpan": { verdict: "confirmed", rationale: "The ITF/8 report says SouthPAN provides Open Services today and 'L1 SBAS Safety-of-Life (SoL) services for aviation are planned from 2028'; the SDD rev 04 gives SoL certification 'Early 2028 (indicative)' after a safety assessment. The SDD also confirms the MT0/2 'do not use for safety applications' broadcast on PRN 122 (Inmarsat 4-F2, 143.5°E) and the Uralla/Awarua uplinks.", checked: [{"source": "SouthPAN SDD SBAS-STN-0001 rev 04 (Apr 2026)", "section": "§4.1 space segment; timeline table; MT0/2 message table", "read": true}, {"source": "ICAO APAC GBAS/SBAS ITF/8 Draft Report (May 2026)", "section": "§4.1 SP/10", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 122, 124", "read": true}] },
  "world.bdsbas": { verdict: "confirmed", rationale: "The 2021 NAVIGATION paper reports initial SF and DFMC services from July 2020 and PRN 130/143/144 assigned to the three BDSBAS GEOs; the FAA sheet says 'In test undergoing certification'. The ITF/8 draft report states 'the LPV procedure will be available around 2029'. The operator is indeed not named as such in the sources read.", checked: [{"source": "NAVIGATION 68(2):405-417 (2021)", "section": "abstract; §2.1.2 ground segment; PRN assignment", "read": true}, {"source": "ICAO APAC GBAS/SBAS ITF/8 Draft Report (May 2026)", "section": "BDSBAS paragraph (p. 7)", "read": true}, {"source": "FAA SBAS Worldwide fact sheet (rev. 11/27/2025)", "section": "BDSBAS box", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 130, 143, 144", "read": true}] },
  "world.sdcm": { verdict: "confirmed", rationale: "Roscosmos' ICG-18 slide states that SDCM 'has successfully passed the preliminary certification tests' for APV-I and APV-II and 'is pre-operational now', with current L1 coverage from LUCH-5B (16°W) and LUCH-5V (95°E); gps.gov maps them to PRN 125 and 140. The claim text is accurate; the card's provider field naming Roscosmos as operator is not supported (see code findings).", checked: [{"source": "Roscosmos, GLONASS Status, ICG-18 (Feb 2024)", "section": "SDCM slide", "read": true}, {"source": "FAA SBAS Worldwide fact sheet (rev. 11/27/2025)", "section": "SDCM box", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 125, 140, 141", "read": true}] },
  "world.anga": { verdict: "corrected", rationale: "A41-WP/298 confirms the demonstration service since September 2020 (Dakar prototype, Abuja uplink, NigComSat-1R) but only says it 'includes a specific message type' against certified receivers. The 'Message Type 0' detail comes from ASECNA's announcement relayed by CANSO (25 Sep 2020: 'a message type MT0'), which is not among the claim's refs. ASECNA's Dec 2024 release gives 'from 2028/29'. Corrected as advised.", checked: [{"source": "ICAO A41-WP/298 (AFCAC, Aug 2022)", "section": "§3.1-3.3", "read": true}, {"source": "ASECNA/SCAA press release (Dec 2024)", "section": "ANGA programme", "read": true}, {"source": "CANSO, ASECNA launch pre-operational SBAS service (25 Sep 2020)", "section": "article text", "read": true}] },
  "world.paksbas": { verdict: "confirmed", rationale: "The ITF/8 report (§4.4, IP/13) says Pak-SBAS was launched in 2019 under SUPARCO with aviation support from PCAA and PAA, the payload launched May 2024, services commissioned September 2024, 'now available for testing', with progressive aviation implementation planned. gps.gov assigns PRN 145 to PakSat-MM1 at 38.2°E. Pakistan's own IP/13 remains unread, so 'to-confirm' status may stay, but the claim text matches the ICAO record.", checked: [{"source": "ICAO APAC GBAS/SBAS ITF/8 Draft Report (May 2026)", "section": "§4.4 IP/13", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 145", "read": true}, {"source": "ICAO APAC ITF/8 IP/13 (Pakistan)", "section": "whole paper", "read": false}] },
  "world.studies": { verdict: "confirmed", rationale: "SAM/IG/15-WP/12 states RLA/03/902 (SACCSA) started in 2003 and its activities were completed at the closing Tenth Coordination Meeting in February 2015; no implementation decision followed. ESA NAVISP says UK SBAS Phase 1 broadcast an ICAO SARPS compliant SIS on PRN 158 via Inmarsat-3F5 (54°W) and Phase 2 is 'Completed'; the UK has no SoL SBAS service.", checked: [{"source": "ICAO SAM/IG/15-WP/12 (Apr 2015)", "section": "§1.5, §2.1", "read": true}, {"source": "ESA NAVISP-EL3-025 project page", "section": "description, status", "read": true}, {"source": "gps.gov L1 C/A PRN Code Assignments (Jan 2026)", "section": "PRN 158", "read": true}] },
  "world.areas": { verdict: "illustrative", rationale: "The outlines are hand-drawn from each provider's wording (e.g. FAA 'Serves North America', KASS 'Incheon FIR', SDD 'magenta line'/ECAC landmasses) and are labelled approximate on screen. That is an acceptable teaching simplification as long as the 'approximate, not an official coverage map' label stays visible next to the map.", checked: [{"source": "FAA SBAS Worldwide fact sheet (rev. 11/27/2025)", "section": "system boxes", "read": true}, {"source": "EGNOS SoL SDD Issue 3.6 (2024)", "section": "§1, service area", "read": true}, {"source": "ICAO APAC ITF/8 IP/07 (Korea)", "section": "§2.1", "read": true}] },
  "world.architecture": { verdict: "confirmed", rationale: "Annex 10 Table 3.7.2.4-1 gives a 6 s time-to-alert for Category I precision approach and, in Note 2, HAL 40 m and a Cat I VAL of 35.0 m to 10.0 m (LPV-200 uses 35 m); APV-I has 10 s, HAL 40 m, VAL 50 m. SDD §3.3.2.1-3.3.2.3 and the FAA describe the RIMS-to-CPF-to-NLES-to-GEO chain, and the SBAS L1 data rate is 250 bit/s with 250-bit messages (one per second).", checked: [{"source": "ICAO Annex 10 Vol I, 8th ed. 2023 (local copy)", "section": "Chapter 3, Table 3.7.2.4-1 and Note 2; App B SBAS data rate", "read": true}, {"source": "EGNOS SoL SDD Issue 3.6 (2024)", "section": "§3.3.2", "read": true}, {"source": "FAA WAAS PAN Report #97 (Jul 2026)", "section": "Table 1-1 service levels", "read": false}, {"source": "FAA WAAS How It Works", "section": "page", "read": false}] },
  "servicemap.real-day": { verdict: "corrected", rationale: "The fetch script takes BRDC00IGS (IGS merged broadcast navigation) and 15 EUREF stations' 30 s observations for 2026-09-30 from igs.bkg.bund.de, matching the claim. 'Geomagnetically quiet' had no source in the refs; GFZ's Kp index for that day (preliminary values) peaks at 0.667, which supports it. Note the map's corrections are modelled (output 'source: modelled'), only the orbits/clocks and station observations are real. Corrected as advised.", checked: [{"source": "scripts/data/fetch-bkg.mjs, src/data/servicemap/2026-09-30.json", "section": "DAY, STATIONS, FILES; source field", "read": true}, {"source": "GFZ Potsdam Kp index, 2026-09-30 (kp.gfz.de JSON, preliminary)", "section": "8 three-hour values, max 0.667", "read": true}] },
  "servicemap.method": { verdict: "corrected", rationale: "The code matches the method: 2° grid, 600 s step, solveFix with K_H,PA 6.0 / K_V,PA 5.33 / K_H,NPA 6.18 (Annex 10 App B 3.5.5.6.1), SPP with broadcast orbits/clocks incl. relativity and T_GD, Klobuchar, DO-229 troposphere and Sagnac. But the 'surveyed position' is the RINEX header APPROX POSITION without the ANTENNA: DELTA H/E/N eccentricity: ACOR and VALE have 3.04 m antenna heights and their stored GPS-alone vertical errors show +2.7 m and +3.1 m median biases. Until fixed, the text overstates the reference. Corrected as advised.", checked: [{"source": "src/core/serviceMap.ts, src/core/spp.ts, src/core/ephemeris.ts, scripts/data/build-service-map.mjs", "section": "levelsAt, solveSpp, satState, station loop", "read": true}, {"source": "Cached EPN RINEX headers (data-cache/bkg/2026-09-30)", "section": "ANTENNA: DELTA H/E/N", "read": true}, {"source": "ICAO Annex 10 Vol I, 8th ed. 2023 (local copy)", "section": "App B 3.5.5.6, 3.5.5.6.1", "read": true}, {"source": "IS-GPS-200", "section": "§20.3.3.4.3, §20.3.3.5.2.5", "read": false}] },
  "servicemap.rims-network": { verdict: "confirmed", rationale: "MPR No. 184 Table 7 ('List of sites where performances are reported') names exactly 32 RIMS (ACR to ZUR), and the code's EGNOS_RIMS has 32 entries at those cities; SDD 3.6 §3.3.2.1 gives 38 RIMS in the full network. The modelled UDRE/GIVE are the page's own model and are labelled 'modelled', which is acceptable.", checked: [{"source": "EGNOS Monthly Performance Report No. 184 (Aug 2026)", "section": "Table 7", "read": true}, {"source": "EGNOS SoL SDD Issue 3.6 (2024)", "section": "§3.3.2.1", "read": true}, {"source": "src/data/servicemap/2026-09-30.json", "section": "rims list (32)", "read": true}] },
  "servicemap.egnos-real": { verdict: "corrected", rationale: "The text understates what the real-message mode leaves out. interpolateGrid only uses four-IGP 5°×5° cells, whereas Annex 10 App B 3.5.5.5.4 requires falling back to 5° triangles and 10° cells, and between N60° and N75° uses 5°-by-10° cells; with the real EGNOS IGP mask (10° longitude spacing north of 60°N) no pierce point there gets a correction, so no LPV would be shown over Iceland or northern Scandinavia, where EGNOS serves to 72°N. groundFromDecoder also ignores MT28 δUDRE, MT6 UDREI updates and MT25 long-term corrections, besides MT7/MT10 degradation. Corrected as advised.", checked: [{"source": "src/core/serviceMap.ts groundFromDecoder; src/core/iono.ts interpolateGrid", "section": "code", "read": true}, {"source": "ICAO Annex 10 Vol I, 8th ed. 2023 (local copy)", "section": "App B 3.5.5.5.3-3.5.5.5.4 (IGP selection and 3-point interpolation)", "read": true}, {"source": "RTCA DO-229", "section": "Appendix A (MT6, MT7, MT10, MT25, MT28)", "read": false}, {"source": "EGNOS SoL SDD Issue 3.6 (2024)", "section": "service area to 72°N", "read": false}] },
  "atc.traffic": { verdict: "illustrative", rationale: "Doc 9613 Vol II Part C Ch 5 Section B 5.2.7.2 c)3) lists 'mixed equipage environment' among the controller core-training items for RNP APCH to LP/LPV, which supports the purpose of the view. The streams, callsigns and equipage are invented and labelled on screen; what each aircraft can fly comes from the same engine, which the code confirms (snapshot/approachMode per aircraft).", checked: [{"source": "ICAO Doc 9613, 5th ed. 2023 (local copy)", "section": "Vol II Part C Ch 5 Section B, 5.2.7.1-5.2.7.3", "read": true}, {"source": "src/scenarios/traffic.ts, src/page/atc/AtcPanel.tsx", "section": "picture()", "read": true}] },
  "training.curricula": { verdict: "confirmed", rationale: "Spot checks match the cited items: ATSEP.BAS.NAV_4.3.1/4.3.5/4.3.6/4.3.7, GNS_1.1.2-1.1.6, FST_2.1.2, PBN_1.1.1 (EAR ATM/ANS), ATCO NAVB 5.3.1-5.3.3 and APP NAV 2.5.1 (EAR ATCO), AMC1/GM1 ATS.OR.525(b) (formal arrangements with ESSP; ESSP certified and overseen by EASA), Doc 9613 5.2.7.2, 5.3.3.1.2, 5.3.4.3.4, 5.3.4.7.2, and Doc 9849 3rd ed. 2.2.2.2, 4.3.1.1, 4.3.3.2, 5.5.5, 7.11.4, App F 5.3.3.4.1. There are 34 links for six objectives. One inconsistency: the mapping uses Doc 9849 3rd edition (2017) numbering, while the sources registry entry 'icao-doc9849' names a different edition.", checked: [{"source": "EASA Easy Access Rules ATM/ANS (Mar 2025) text", "section": "AMC App 2a/3a/4a; AMC1/GM1 ATS.OR.525(b)", "read": true}, {"source": "EASA Easy Access Rules ATCO (Mar 2024) text", "section": "NAVB 5.3; APP NAV 2.5.1", "read": true}, {"source": "ICAO Doc 9613, 5th ed. 2023 (local copy)", "section": "Vol II Part C Ch 5 Section B", "read": true}, {"source": "ICAO Doc 9849, 3rd ed. 2017 (local copy)", "section": "2.2.2.2, 4.3.1.1, 4.3.3.2, 5.5.5, 7.11.4, App F", "read": true}] },
  // GNSS
  'gnss.four-satellites': { verdict: 'confirmed', rationale: 'Four unknowns (three coordinates and the receiver clock offset) need at least four pseudo-ranges, and the DOP turns range errors into position errors; the receiver code gives no fix with fewer than four satellites. Textbook GNSS, checked from expertise: Doc 9849 §3.1 itself was not read.', checked: [known(D9849_5, '§3.1')] },
  'gnss.constellation': { verdict: 'confirmed', rationale: 'The GPS SPS Performance Standard (read) gives 24 baseline slots in six planes, 55° inclination and a 26 559.8 km semi-major axis, about 20 180 km above the equator, with an orbit of half a sidereal day. The model’s 20 200 km gives 11.98 h instead of 11.97 h, negligible for teaching; the SPS PS is now cited.', checked: [read(SPSPS, '§3.2, Tables 3.2-1 and 3.2-3'), read(GPSGOV), known(D9849_5, '§3.2.2')] },
  'gnss.slot-phasing': { verdict: 'corrected', rationale: 'The text is right: the SPS PS slot table (read) has uneven arguments of latitude in each plane (plane A: 13.22°, 133.20°, 239.54°, 343.09°), and the model’s even Walker 24/6/1 pattern is a labelled simplification. The source was wrong: IS-GPS-200 defines the signal, not the slots, so the claim now cites the SPS PS. Both reviewers agree.', checked: [read(SPSPS, '§3.2, Table 3.2-1'), read(ISGPS, 'whole document (no slot table)')] },
  'gnss.constellation-size': { verdict: 'illustrative', rationale: 'gps.gov (read) gave 31 operational satellites in July 2023 against a commitment of at least 24, so "about 31" holds. Flying the nominal 24 makes RAIM gaps more frequent, and starting each scenario at a typical geometry is an honest, labelled modelling choice. Doc 9849 §4.3.4.3 was not read.', checked: [read(GPSGOV, '31 operational satellites, 3 July 2023'), known(D9849_5, '§3.2.2, §4.3.4.3')] },
  'gnss.l5-everywhere': { verdict: 'illustrative', rationale: 'IS-GPS-200N §6.2.5 (read) says only Block IIF and later satellites broadcast L5; the claim says the model simplifies that. GPS L5 is also not yet declared operational for safety-of-life use, which the note now says; its status should be checked on gps.gov before a presentation.', checked: [read(ISGPS, '§6.2.5'), read(GPSGOV, 'satellite generations'), known(D9849_5, '§3.2.4')] },
  'gnss.frequencies': { verdict: 'confirmed', rationale: 'IS-GPS-200N (read) gives L1 at 1575.42 MHz (§3.3.1.1) and L5 at 1176.45 MHz (§6.2.5; the L5 signal itself is in IS-GPS-705); all GPS satellites share the carriers (CDMA). The code holds exactly these values.', checked: [read(ISGPS, '§3.3.1.1, §6.2.5'), known(D9849_5, '§3.2.4')] },
  'gnss.speed-of-light': { verdict: 'confirmed', rationale: 'IS-GPS-200N (read) uses c = 2.99792458 × 10⁸ m/s in its user algorithms; the value is exact because the SI metre is defined from it. The code matches.', checked: [read(ISGPS, '§20.3.3.3.3.1')] },
  'gnss.wgs84': { verdict: 'confirmed', rationale: 'a = 6 378 137.0 m and 1/f = 298.257223563 are two of the four WGS-84 defining parameters. Confirmed through search results quoting NGA and the ICG WGS 84 summary, not from TR8350.2 itself; the values are well established and the code matches to 1e-12.', checked: [known('NIMA TR8350.2', 'Table 3.1'), known('UNOOSA/ICG WGS 84 summary (search result)')] },
  'gnss.earth-rotation': { verdict: 'confirmed', rationale: 'WGS-84 defines ω = 7 292 115 × 10⁻¹¹ rad/s, and IS-GPS-200N Table 20-IV (read) gives 7.2921151467 × 10⁻⁵ rad/s for the GPS user equations. The IS-GPS value is needed only when computing positions from the broadcast ephemeris; on the model’s idealised orbits the difference is below a millimetre, so the open question in the text is closed.', checked: [read(ISGPS, 'Table 20-IV'), known('NIMA TR8350.2', 'Table 3.1')] },
  'gnss.mu': { verdict: 'confirmed', rationale: 'IS-GPS-200N Table 20-IV (read) gives μ = 3.986005 × 10¹⁴ m³/s² as the WGS 84 value for GPS users. The current WGS-84 GM is 3.986004418 × 10¹⁴, but GPS deliberately keeps the older value, so "used for GPS orbits" is the right wording.', checked: [read(ISGPS, 'Table 20-IV; §20.3.3.3.3.1')] },
  'gnss.errors': { verdict: 'confirmed', rationale: 'These are the standard range-error sources, the ionosphere usually the largest on L1. SBAS corrects clock, orbit and (on its grid) the ionosphere, the receiver models the troposphere, and multipath and noise enter only its error bound. Checked from expertise; Doc 9849 §4.3.1.1 and §5.2.1 were not read.', checked: [known(D9849_5, '§4.3.1.1, §5.2.1')] },
  'gnss.error-sizes': { verdict: 'corrected', rationale: 'As illustrative values they are acceptable: the truth is drawn at about 0.95 m 1σ (about 1.9 m 95 %), consistent with the SPS PS commitment of 2.0 m 95 % for the ensemble of constellation slots (Table 3.4-1 also gives 7.0 m 95 % per satellite). IS-GPS-200 has no error budget, so the claim now cites the SPS PS; the second reviewer sharpened which SPS PS figure applies.', checked: [read(SPSPS, '§3.4.1, Table 3.4-1'), read(ISGPS, 'whole document (no error budget)')] },
  'gnss.troposphere-model': { verdict: 'confirmed', rationale: 'The mapping 1.001/√(0.002001 + sin²E) and the 0.12 m zenith residual σ are the RTCA MOPS tropospheric model (Navipedia, read, confirms the mapping; search results the 0.12 m). The MOPS adds a small term below 4° elevation, irrelevant at the 5° mask. DO-229 was not read, so a reviewer with it should sign off.', checked: [known(DO229, 'Appendix A'), read('ESA Navipedia, Tropospheric Delay', 'SBAS model'), known(A10, 'Appendix B, residual tropospheric error')] },
  'gnss.airborne-multipath': { verdict: 'corrected', rationale: 'The multipath model 0.13 + 0.53·e^(−θ/10°) m is the standard airframe model (Annex 10 App B 3.6.5.5.1.1.2, applied to SBAS by the Note to 3.5.8.4.2), and 0.36 m is the receiver-noise limit at minimum signal power, 0.15 m at maximum (App B 3.5.8.4.1); the second reviewer read both. The "AAD-A-like" label was replaced: Att D 6.3.9 does use GBAS AAD-A for SBAS service prediction, but AAD-A varies with elevation while the code’s 0.36 m is the constant SBAS limit.', checked: [read(A10, 'App B 3.5.8.4.1, 3.6.5.5.1.1.2; Att D 6.3.9'), known(DO229, 'Appendix J')] },

  // SBAS
  'sbas.reference-stations': { verdict: 'confirmed', rationale: 'The standard description of the SBAS ground segment: reference stations (RIMS in EGNOS) at surveyed positions over a wide area monitor the GNSS signals and send their measurements to the master stations. The EGNOS SoL SDD (read) describes its RIMS network the same way.', checked: [read(SDD, '§3'), known(D9849_5, '§4.3.1.1')] },
  'sbas.master-corrections': { verdict: 'confirmed', rationale: 'Master stations compute satellite clock and orbit corrections, vertical ionospheric delays at the grid points, and integrity bounds on what is left (UDRE, GIVE), as the SARPs describe and Walter’s WAAS MOPS examples (read) show.', checked: [read(WALTER, 'clock, ephemeris and ionospheric corrections'), known(D9849_5, '§4.3.1.1, §4.3.1.4.2')] },
  'sbas.udre-give': { verdict: 'confirmed', rationale: 'UDRE (via UDREI) bounds each satellite’s residual clock and orbit error at 99.9 %, GIVE (via GIVEI) the residual vertical ionospheric error at each grid point; the receiver turns both into variances for its protection levels, as RTKLIB’s DO-229 implementation (read) does.', checked: [read(RTKLIB, 'varfcorr(), varicorr()'), read(WALTER, 'UDRE degradation; ionospheric corrections'), known(D9849_5, '§4.3.1.4.2')] },
  'sbas.do-not-use': { verdict: 'corrected', rationale: 'Annex 10 App B 3.5.8.1.2.12 (read by the second reviewer) says the receiver shall no longer use a satellite for SBAS precision approach or APV if its UDREI is 12 or more; the claim and the code had allowed UDREI 12. The claim now says so and the receiver rule (groundSegment.usableForPa) refuses UDREI ≥ 12 for LNAV/VNAV and LPV. Doc 9849 §4.3.1.3 covers only Do Not Use and Not Monitored, so there is no conflict; LP is left out until DO-229 is checked.', checked: [read(A10, 'App B 3.5.8.1.2.12'), read(D9849, '§4.3.1.3'), read('FAA WAAS Discrepancy Report #91 (2010)', 'p. 1')] },
  'sbas.udre-table': { verdict: 'confirmed', rationale: 'The 14 UDRE values (0.75 to 150 m for UDREI 0–13; 14 Not Monitored, 15 Do Not Use) are the UDREI table; RTKLIB’s DO-229 variance table (read) is exactly (UDRE/3.29)² for these values. The DO-229 table number was not checked against the text.', checked: [read(RTKLIB, 'varfcorr() σ²_UDRE table'), read(WALTER, 'Table 2'), known(DO229, 'Table A-6'), known(A10, 'Appendix B, UDREI table')] },
  'sbas.sigma-udre': { verdict: 'confirmed', rationale: 'The tabulated σ²_UDRE at UDREI 0 is 0.0520 m² and (0.75/3.29)² = 0.05197 m²; the whole column equals (UDRE/3.29)² rounded up in the fourth decimal, 3.29 being the two-sided 99.9 % Gaussian factor.', checked: [read(RTKLIB, 'varfcorr()'), read(WALTER, 'Table 2'), known(DO229, 'Table A-6')] },
  'sbas.give-table': { verdict: 'confirmed', rationale: 'The 15 GIVE values (0.3 to 45 m for GIVEI 0–14; 15 Not Monitored) match the GIVEI table, and RTKLIB’s σ²_GIVE table (read) equals (GIVE/3.29)² for exactly these. The value array ends with the Not Monitored index 15, which the unit "m" does not make clear.', checked: [read(RTKLIB, 'varicorr() σ²_GIVE table'), known(DO229, 'Table A-17')] },
  'sbas.sigma-give': { verdict: 'confirmed', rationale: 'DO-229 tabulates σ²_GIVE = 0.0084 m² at GIVEI 0 (RTKLIB’s copy, read); GIVE/3.29 gives 0.00831 m², about 1 % lower because the standard rounds its variances up. The difference is inside the claim’s 2 % tolerance and does not matter for teaching.', checked: [read(RTKLIB, 'varicorr()'), known(DO229, 'Table A-17')] },
  'sbas.igp-grid': { verdict: 'confirmed', rationale: 'In IGP bands 0–8 the grid points are every 5° between 55°S and 55°N and wider poleward (RTKLIB’s band tables, read). Both scenarios’ grids lie inside 55°S–55°N, so a uniform 5° grid is right for them.', checked: [read(RTKLIB, 'igpband1, igpband2 (DO-229 IGP bands)'), known(DO229, 'Appendix A, IGP bands')] },
  'sbas.iono-shell': { verdict: 'confirmed', rationale: 'The SBAS user algorithm puts the pierce point on a thin shell 350 km above an Earth of radius 6378.1363 km and derives the obliquity from the same geometry; RTKLIB’s DO-229 implementation (read) uses exactly these constants.', checked: [read(RTKLIB, 'sbsioncorr()'), known(DO229, 'Appendix A')] },
  'sbas.geo-broadcast': { verdict: 'confirmed', rationale: 'Uplink stations (NLES in EGNOS) send the message stream to the GEOs, which rebroadcast it; a GEO stays over the equator at a nominally fixed longitude, drifting slightly inside its station-keeping box, which the page can ignore. The EGNOS SoL SDD (read) describes the space segment the same way.', checked: [read(SDD, '§3 (space segment)'), known(D9849_5, '§4.3.1.2')] },
  'sbas.message-rate': { verdict: 'confirmed', rationale: 'Each GEO sends one 250-bit message a second, rate-½ encoded to 500 symbols/s; an L1 message is an 8-bit share of the 24-bit preamble, a 6-bit type, 212 data bits and a 24-bit CRC. The Annex 10 App B text read gives the preamble and the data field, the symbol rate and FEC come from expertise, and the recorded EGNOS messages confirm the layout.', checked: [read(DRAFT, 'App B 3.5.3.1–3.5.3.2'), read(WALTER, 'abstract (250-bit messages every second)'), known(DO229, 'Appendix A')] },
  'sbas.dfmc-layout': { verdict: 'confirmed', rationale: 'On L5 the 24-bit preamble is spread over six messages, so each carries 4 preamble bits, a 6-bit type, 216 data bits and a 24-bit CRC, 250 bits a second; the draft DFMC Annex 10 text (read) shows this. Type 50 (authentication) is the one exception, without a CRC, which does not matter here.', checked: [read(DRAFT, 'App B 3.5.10.1–3.5.10.3; L5 message tables'), known(ED259, 'message format')] },
  'sbas.message-types': { verdict: 'confirmed', rationale: 'All numbers and names match the Annex 10 tables of L1 and L5 message types (read in the draft amendment). Minor naming nits: Type 39 is "SBAS satellite clock, ephemeris and covariance matrix, part 1", and Type 37 also carries the DFREI scale table.', checked: [read(DRAFT, 'L1 message type table; Table B-98'), known(DO229, 'Appendix A'), known(ED259)] },
  'sbas.mt0': { verdict: 'confirmed', rationale: 'Type 0 means Do Not Use (test mode): the receiver drops that SBAS satellite’s data for at least a minute. Type 27 or 28 on L1 (a provider sends one or the other) and the covariance in Type 32 on L5 make the bound depend on the user’s position, as the claim says.', checked: [read(DRAFT, 'App B 3.5.8.1.2; message type tables'), known(D9849_5, 'Appendix G 2.5; §4.3.4.2')] },
  'sbas.timeouts': { verdict: 'corrected', rationale: 'Re-checked after the text added the four-lost-messages rule. Annex 10 App B Table B-94 (read in the 8th edition by the second reviewer) gives the integrity data (UDREI) 12 s for precision approach and APV and 18 s for en route, terminal and NPA, long-term corrections 240/360 s and Type 26 600 s; the fast corrections time out after I_fc from Type 7 (Table B-95); 3.5.8.1.2.7, read in the same pass, invalidates all UDREI data after four successive lost messages with HAL ≤ 40 m or VAL ≤ 50 m, which the GEO-loss behaviour now applies (it had kept LPV for the full 12 s). The WAAS PAN report #92 Table 5-3, read for this re-check, gives the same 12/18, 240/360 and 600 s.', checked: [read(A10, 'App B Tables B-94, B-95; 3.5.8.1.2.7–3.5.8.1.2.8'), read('FAA WAAS PAN Report #92 (April 2025)', 'Table 5-3'), read(DRAFT, 'Table B-94; Table B-119 (L5)'), read(WALTER, 'message time-out periods'), known(DO229, 'Table A-25')], on: '2026-10-07' },
  'sbas.alarm-latency': { verdict: 'illustrative', rationale: 'The 2.5 s detection and 1.2 s uplink latencies are not specified values, and the claim labels them so. In the code the aircraft gets the alarm at most about 5.7 s after the fault, within the 6 s time to alert of Category I and APV-II and the 10 s of APV-I, so the page does not mislead.', checked: [read(WALTER, 'introduction (6 s time to alarm)'), known(D9849_5, 'Table 2-1')] },
  'sbas.operations-supported': { verdict: 'confirmed', rationale: 'The SARPs define the SBAS functions as ranging, satellite status, basic differential correction (clock and orbit) and precise differential correction (adding the ionospheric grid); status and basic corrections support departure to NPA, precise corrections APV and Category I. Checked from expertise; the cited sections were not read.', checked: [known(D9849_5, '§4.3.1.5'), known(A10, 'Ch. 3 §3.7.3.4')] },
  'sbas.protection-levels': { verdict: 'confirmed', rationale: 'The receiver combines σ_flt (from UDRE and degradation), σ_UIRE (from GIVE) and its own airborne and troposphere models into HPL and VPL, and the operation is available only while each stays within HAL and VAL: the standard SBAS integrity check, as Walter’s examples (read) show.', checked: [read(WALTER, 'σ_flt bound figures'), known(D9849_5, '§4.3.2.4, §2.2.4.3')] },
  'sbas.k-factors': { verdict: 'confirmed', rationale: 'K_H,NPA = 6.18, K_H,PA = 6.0 and K_V,PA = 5.33, with HPL = K_H·d_major and VPL = K_V·d_V, are the SBAS protection-level equations as known from DO-229 and Annex 10; Walter’s paper (read) plots the 5.33σ vertical bound. The exact paragraphs were not checked.', checked: [known(DO229, 'Appendix J'), known(A10, 'Appendix B, protection level equations'), read(WALTER, 'Figures 1–4')] },
  'sbas.raim': { verdict: 'corrected', rationale: 'Both reviewers recomputed independently: the χ² thresholds (19.51 … 41.30) match a false-alarm probability of 10⁻⁵ for 1–10 degrees of freedom, but the protection-level factors 5.4 … 7.2 gave a missed-detection probability of 0.08–0.16, not 10⁻³. The code now uses √λ for 10⁻³ (7.51 … 8.92), which raises the RAIM HPL by 24–39 %, and the text states both probabilities. DO-229’s false-alert requirement (per hour, not per epoch) was not read, so the per-epoch figure stays a labelled simplification.', checked: [read('Own computation (non-central χ²)', '√λ for Pfa 10⁻⁵, Pmd 10⁻³, 1–10 degrees of freedom'), read(D9849, '§1.4.2.2'), known(DO229, '§2.1 FDE requirements')] },
  'sbas.mask-angle': { verdict: 'corrected', rationale: 'Annex 10 App B 3.5.8.1.2.11 (read) says that for SBAS precision approach or APV the receiver uses only satellites at or above 5°; it sets no mask for en route or NPA, and none for reference stations. The claim said satellites below 5° are "not tracked" by aircraft and stations alike; it now cites the paragraph and labels the all-phases and RIMS mask as the page’s simplification. The EGNOS SoL SDD §6 (read) assumes the same 5°.', checked: [read(A10, 'App B 3.5.8.1.2.11'), read(SDD, '§6'), known(DO229, 'mask angle')] },
  'sbas.abas-iono-sigma': { verdict: 'corrected', rationale: 'Annex 10 App B 3.5.5.6.3.2 (read, page image checked) gives σ = max(T_iono/5, F_pp·τ_vert) with τ_vert 9 m within 20° of the equator, 4.5 m from 20° to 55° and 6 m beyond, on the geographic latitude of the pierce point (the first reviewer’s recollection of DO-229 said magnetic latitude). The code used 9 m everywhere, twice the standard value over Europe; one shared function (iono.sigmaIonoNoSbasM) now serves GPS alone, L1 SBAS satellites outside the grid and the service maps. Applying it to ABAS RAIM is a labelled modelling choice.', checked: [read(A10, 'App B 3.5.5.6.3.2'), known(DO229, 'Appendix J (J.2.3)')] },
  'sbas.dfre': { verdict: 'illustrative', rationale: 'DFMC SBAS bounds each satellite with DFRE (a DFREI in Types 32 and 34–36, scaled by the table in Type 37); the page reuses the L1 UDRE bound and says so. That changes only the size of the dual-frequency protection levels, not the idea, and is acceptable for teaching.', checked: [read(DRAFT, 'Table B-98 (Types 34–37), Table B-119'), known(ED259, 'DFREI table')] },
  'sbas.mode-annunciation': { verdict: 'confirmed', rationale: 'SBAS avionics annunciate the approach service level the signal currently supports (LPV, LNAV/VNAV, LNAV). The full list also has LP and advisory "+V" modes, but neither scenario has an LP procedure, so leaving them out does not mislead.', checked: [known(D9849_5, '§4.3.2.5')] },
  'sbas.fas-crc': { verdict: 'confirmed', rationale: 'The FAS data block defines the LPV/LP final approach path in the navigation database, and a 32-bit CRC inside it lets the avionics detect any corruption; the EUROCONTROL FAS tool (read) lists the CRC as part of the block.', checked: [read(FASDB, 'Encode (CRC value)'), known(D9849_5, '§4.3.2.7')] },
  'sbas.fas-fields': { verdict: 'corrected', rationale: 'Every field named is a real FAS field, but the list read as complete and left out the flight path alignment point, which with the threshold sets the final approach course. Annex 10 App B Table B-96 (read) lists the fields; the claim now names the main ones and the allowed course width, 80 to 143.75 m in 0.25 m steps (Doc 8168 Vol II’s worked example uses 105 m).', checked: [read(A10, 'App B Table B-96 and field definitions'), read('ICAO Doc 8168 Vol II', 'FAS data block guidance'), read(FASDB, 'Encode field list'), known(DO229, 'Appendix D')] },
  'sbas.fas-crc32q': { verdict: 'confirmed', rationale: 'The FAS data block CRC uses the 32-bit "Q" polynomial, 0x814141AB without the x³² term; the binding is valid because the CRC of the single byte 0x01 (MSB first, zero start) is the polynomial. The page computes it over a text encoding rather than the bit-packed block, an acknowledged simplification.', checked: [known(DO229, 'Appendix D (FAS CRC)'), known(A10, 'Appendix B, FAS data block CRC')] },
  'sbas.channel': { verdict: 'confirmed', rationale: 'Each SBAS approach has a five-digit channel number the crew can enter to select it, as with GBAS. Checked from expertise; Doc 9849 §4.3.2.9 was not read.', checked: [known(D9849_5, '§4.3.2.9')] },
  'sbas.channel-range': { verdict: 'confirmed', rationale: 'SBAS channels run from 40 000 to 99 999 (GBAS uses 20 001 to 39 999), and both scenario channels (54201, 40642) fall in the SBAS range. The paragraph number in Annex 10 or DO-229 was not checked.', checked: [known(DO229, 'channel number assignment'), known(A10, 'Appendix B, SBAS channel number')] },
  'sbas.lpv-deviations': { verdict: 'corrected', rationale: 'Annex 10 (read: the FAS data block note, Att D 7.11.3.1–7.11.3.2, Figure D-15) makes the lateral deviation angular about the azimuth reference point 305 m beyond the FPAP, with full scale equal to the course width at the threshold; the vertical full scale is 0.25 × the glide path angle. The code splayed linearly at about half that rate; it now widens the full scale as CW·(d + D)/D. The ±1 NM limit is in neither Annex 10 nor Doc 8168, so it stays in the code labelled to confirm against DO-229.', checked: [read(A10, 'App B FAS data block note; Att D 7.11.3.1–7.11.3.2; Figure D-15'), read('ICAO Doc 8168 Vol II', 'FPAP and GARP, §6.4.3'), known(DO229, 'LPV/LP deviations')] },
  'sbas.decision-height': { verdict: 'illustrative', rationale: 'Each procedure sets its own decision height, and the page labels both values illustrative: 250 ft is typical of an APV-I LPV with VAL 50 m (Bali), and 200 ft needs the 35 m VAL of LPV-200 (Nice). Both match the scenarios’ alert limits.', checked: [known(D9849_5, '§4.3.3.3')] },
  'sbas.two-geos': { verdict: 'corrected', rationale: 'Doc 9849 §4.3.2.10 and Appendix G §2.4.1 (read) require the avionics to track the GEOs broadcasting corrections and to be able to switch quickly; the EGNOS SoL SDD §3.3.1 (read) says two operational GEOs secure a switching capability. As written, the claim read as if LPV were lost with one GEO; it now says one satellite with current data is enough, which is what the model does.', checked: [read(D9849, '§4.3.2.10; Appendix G §2.4.1'), read(SDD, '§3.3.1'), known(DO229, 'dual SBAS tracking')] },
  'sbas.abas-fallback': { verdict: 'confirmed', rationale: 'When SBAS integrity is unavailable, SBAS avionics revert automatically to GPS with RAIM/FDE for en route to LNAV and lose the vertical SBAS modes, as DO-229 equipment does; the EGNOS SoL SDD (read) describes the same reversion.', checked: [read(SDD, 'SBAS avionics use of GPS RAIM/FDE'), known(D9849_5, '§4.3.4.3')] },
  'sbas.no-airport-equipment': { verdict: 'confirmed', rationale: 'An SBAS approach needs no navigation aid at the airport: the signal comes from the GEOs and the path from the FAS data block in the database. The airport still needs a surveyed, published procedure, but no dedicated equipment.', checked: [known(D9849_5, '§4.3.3.1')] },
  'sbas.cat1-200ft': { verdict: 'corrected', rationale: 'The first reviewer could not trace the WAAS statistic; the second found it in Doc 9849 (3rd ed.) §4.3.3.3: in more than 1.76 billion observations with a VAL of 35 m or less, the largest WAAS signal-in-space vertical error was 8.9 m. Annex 10 Table 3.7.2.4-1 Note 2 (read) gives the Category I VAL as 35 to 10 m, a value above 10 m only after a system-specific safety analysis (Att D 3.3.6). The text now says what the statistic measured; its 5th-edition section number is to confirm.', checked: [read(D9849, '§4.3.3.3'), read(A10, 'Ch. 3 Table 3.7.2.4-1 Note 2; Att D 3.3.6')] },

  // Operations, ATM and the ionosphere
  'ops.alert-limits': { verdict: 'confirmed', rationale: 'Every value matches Annex 10 Vol I Table 3.7.2.4-1 and its Note 2 and Doc 9849 Table 2-1, both read: HAL 7.4 km, 3.7 km, 1.85 km, 556 m and 40 m, VAL 50 m, 20 m and 35–10 m, and the times to alert. "SBAS uses 35 m" agrees with Att D 3.3.6 and the FAA WAAS Performance Standard’s LPV-200 VAL.', checked: [read(A10, 'Ch. 3 Table 3.7.2.4-1 and Note 2; Att D 3.3.6–3.3.8'), read(D9849, 'Table 2-1'), read(NAVIPEDIA_WAAS)] },
  'ops.lnavvnav': { verdict: 'confirmed', rationale: 'The FAA WAAS Performance Standard (through ESA Navipedia, read) gives LNAV/VNAV HAL 556 m and VAL 50 m, matching the code. Doc 9613 (read) confirms SBAS vertical guidance may serve LNAV/VNAV minima, and Doc 9849 Table 2-1 Note 3 that these are not Annex 10 table values. DO-229 was not read, so a reviewer with it should tick the claim.', checked: [read(NAVIPEDIA_WAAS), read(D9613, 'Vol II, RNP APCH, 5.3.3.3.1.2 a) Note'), read(D9849, 'Table 2-1 Note 3'), known(DO229, 'LNAV/VNAV alert limits')] },
  'ops.time-to-alert': { verdict: 'confirmed', rationale: 'Annex 10 Ch. 3 definitions and Doc 9849 (3rd ed.) §2.2.2.3, both read, define the time to alert as the longest time from the system being out of tolerance to the alert in the aircraft; the plain wording matches. The cited 5th-edition section §2.2.4.4 was not checked.', checked: [read(A10, 'Ch. 3 §3.7.1, time-to-alert'), read(D9849, '§2.2.2.3'), known(D9849_5, '§2.2.4.4')] },
  'ops.adsb': { verdict: 'corrected', rationale: 'Doc 9849 §1.4.3 (read) supports ADS-B broadcasting the GNSS position. The integrity ADS-B carries (NIC) comes from the receiver’s horizontal protection level, not from the alert limits, and the ground system checks it against what the surveillance service needs; the text now says so. NIC from the protection level is DO-260B practice, from both reviewers’ expertise, not read.', checked: [read(D9849, '§1.4.3'), known('RTCA DO-260B / EUROCAE ED-102A', 'NIC encoding')] },
  'ops.notam': { verdict: 'confirmed', rationale: 'Annex 10 Att D 6.2.6 (read) expects a State to provide status monitoring and a NOTAM system, using a service volume model, before publishing SBAS procedures, and Doc 9849 (3rd ed.) §7.11 (read) says the same. Annex 10 is now cited as the primary source; the 5th-edition section number was not checked.', checked: [read(A10, 'Att D 6.2.6'), read(D9849, '§7.11.1, §7.11.4'), known(D9849_5, '§4.3.3.4.1')] },
  'ops.gnss-loss-fallback': { verdict: 'corrected', rationale: 'Doc 9849 §7.13.2.1 (read) lists on-board equipment such as IRS, conventional aids and radar, and procedural methods by aircrew and/or ATC, and names DME/DME updating, VOR/DME and ILS. The claim left out radar and used "procedural control", an ATC term the source does not use; it now follows the source.', checked: [read(D9849, '§7.13.2.1–7.13.2.5')] },
  'ops.space-weather': { verdict: 'confirmed', rationale: 'ICAO space weather advisories (Annex 3, guidance in Doc 10100) cover HF COM, SATCOM, GNSS and radiation, and the GNSS advisory is driven by scintillation and vertical TEC; this is from expertise, as Annex 3 and Doc 10100 were not read. Doc 4444 §9.1.3.8 (read) requires ATS units to pass on space weather information affecting GNSS.', checked: [known('ICAO Annex 3 / Doc 10100', 'GNSS advisory'), read(D4444, '§9.1.3.8'), known(D9849_5, '§7.13.3')] },
  'ops.abas-lnav': { verdict: 'corrected', rationale: 'Doc 9849 §1.4.2.2 (read) says ABAS supports RNP APCH to LNAV minima and, with Baro-VNAV, to LNAV/VNAV minima. As written, the claim implied that aircraft with GPS alone never fly vertically guided approaches; it now says vertical guidance needs Baro-VNAV or SBAS. "No vertical protection level" is right for GNSS alone.', checked: [read(D9849, '§1.4.2.2; Table 2-1 Notes 1 and 3')] },
  'atc.phraseology': { verdict: 'corrected', rationale: 'Read in Doc 4444 (16th ed. incl. Amendment 8) §12.3.1.14–12.3.1.15: the controller phrases, the SBAS phrase "SBAS UNAVAILABLE FOR (specify operation)" and the crew’s "UNABLE RNP (specify type) [DUE TO (reason)]". The claim had been written from memory; it now quotes the paragraphs with their sections. ICAO APAC guidance of August 2026 (read) quotes the same words; later amendments are still to confirm.', checked: [read(D4444, '§12.3.1.14, §12.3.1.15'), read('ICAO APAC GNSS RFI guidance v1.0 (Aug 2026)', 'Ch. 10 phraseology')] },
  'iono.storm': { verdict: 'corrected', rationale: 'Doc 9849 §5.5.1–5.5.2 (3rd ed., read) ties the delay to time of day, season and the 11-year cycle, and says rare storms cause large, rapid variations over a wide area. "Thicker" was only half true, since storms can lower the electron content as well as raise it; the text now says the delay changes fast and unevenly, and the storm failure texts follow it.', checked: [read(D9849, '§5.5.1, §5.5.2'), known(D9849_5, '§5.2.1.1, §5.2.1.2')] },
  'iono.equatorial-l1': { verdict: 'confirmed', rationale: 'Doc 9849 (3rd ed., read) §5.5.5 describes dense bands about 15° either side of the magnetic equator and post-sunset bubbles, and says single-frequency SBAS APV is not practical there; Category I follows a fortiori. GAGAN’s APV-I certification shows that "impractical" means "not with high availability".', checked: [read(D9849, '§5.5.5, §4.3.1.4, Executive Summary'), known(D9849_5, '§5.2.1.5, §4.3.1.4')] },
  'iono.scintillation': { verdict: 'confirmed', rationale: 'Doc 9849 §5.5.3–5.5.4 (3rd ed., read): severe scintillation is fairly common near the equator after sunset and before midnight, occurs in patches, affects only a few satellites at a time and affects all GNSS frequencies. The claim matches point by point.', checked: [read(D9849, '§5.5.3, §5.5.4'), known(D9849_5, '§5.2.1.3, §5.2.1.4')] },
  'iono.dfmc-removes-delay': { verdict: 'confirmed', rationale: 'The ionosphere-free combination removes the first-order delay (Annex 10 Ch. 3 definition, read). With equal, independent noise on L1 and L5 the noise factor is √(γ² + 1)/(γ − 1) with γ = (f1/f5)² = 1.7933, i.e. 2.588, which the code computes exactly. The value rests on that derivation, since the 3rd edition of Doc 9849 does not give it.', checked: [read(A10, 'Ch. 3 §3.7.1, ionosphere-free pseudo-range; App B 3.1.1.2.2.7'), read(D9849, '§6.2.5'), known(D9849_5, '§4.3.1.4.1, §5.2.1.6')] },
  'iono.broadcast-model': { verdict: 'confirmed', rationale: 'Doc 9849 §5.5.6 (3rd ed., read): the broadcast model reduces the ionospheric error by a factor of about two, and SBAS reduces it to a few metres with assured integrity. "Removes about half" and "bounds it" are faithful plain-language versions.', checked: [read(D9849, '§5.5.6'), known(D9849_5, '§5.2.1.6')] },
  'iono.threat-model': { verdict: 'illustrative', rationale: 'The threat sizes in iono.ts are labelled illustrative and tuned to reproduce Doc 9849’s qualitative conclusion (§5.5.5, read: single-frequency APV is not practical near the equator). No standard specifies them, and real GIVE threat models are system-specific and not public in this form, so this is acceptable for teaching.', checked: [read(D9849, '§5.5.5'), known(D9849_5, '§5.2.1.5')] },
  'iono.dip-equator': { verdict: 'corrected', rationale: 'Both reviewers computed the dip equator (inclination zero) from IGRF-14 at epoch 2025.0 independently and got the same table: over Indonesia it lies at about 6.5–8°N, not 9–10°N, so the map-read table was 2.5–3.3° too far north at 90–120°E. The code now uses the IGRF-14 table, which moves Indonesia’s equatorial bands south (the recorded AirNav Indonesia values change, tests/golden). At the 350 km shell height the line moves by at most 0.25° over 90–140°E.', checked: [read('IGRF-14 via ppigrf 2.1.0 (own computation)', 'inclination zero, epoch 2025.0, every 15° of longitude')] },
  'dfmc.planned': { verdict: 'corrected', rationale: 'No DFMC SBAS safety-of-life service is operational. The FAA’s April 2026 CGSIC briefing (read) gives WAAS dual-frequency LOC about 2026, IOC about 2027 and FOC about 2028, and EUSPA’s 2026 roadmap (read) puts the EGNOS v3 DFMC service (V3.2) in the early 2030s; "EGNOS from 2028" had dated DFMC to the L1-only V3.1 release. The second reviewer preferred the 2026 EUSPA roadmap to EUSPA’s 2024 "about 2029", so this claim and egnos.v3-dfmc agree.', checked: [read('FAA CGSIC briefing (April 2026)', 'WAAS Phase 4 DFO status'), read('EUSPA Industry Days 2026 deck', 'roadmaps, p. 9–10'), read('EUSPA, EGNOS new services (March 2024)', 'V3 releases'), read(D9849, '§4.3.4.5.3')] },
  'dfmc.equatorial-apv': { verdict: 'corrected', rationale: 'Doc 9849 §6.2.5 (3rd ed., read) says future DFMC SBAS would be able to support nearly 100 % APV availability even in equatorial regions, and §5.5.3 that scintillation still affects all frequencies. The claim stated it as present fact for a service not yet in operation; it is now an expectation.', checked: [read(D9849, '§6.2.5, §5.5.3'), known(D9849_5, '§6.8.2')] },

  // EGNOS and ESSP
  'essp.provider': { verdict: 'corrected', rationale: 'ESSP is the EGNOS service provider for the Open Service and the SoL service (SoL SDD §3.4.1, read). EUSPA’s EGNOS Workshop 2022 slide (read by the second reviewer) records a contract of up to ten years signed with ESSP in July 2022, so the date stands, but EUSPA described the EDAS hand-over as in progress in 2022, so "took over" became "said it was taking over".', checked: [read('EUSPA, EGNOS Programme Status (EGNOS Workshop 2022)', 'New EGNOS Service Provision Phase'), read('EUSPA news item (6 September 2022)'), read(SDD, '§3.4.1')] },
  'egnos.geos': { verdict: 'corrected', rationale: 'Service Notice 33 Table 1 and SoL SDD v3.6 Table 2 (both read) give GEO-1 SES-5 (PRN 136, 5°E) and GEO-3 Eutelsat 5 West B (PRN 121, 5°W) operational, and GEO-2 ASTRA 5B (PRN 123) in test since 5 September 2025, at 23.5°E. The claim’s 31.5°E came from the gps.gov PRN list, which still shows the slot ASTRA 5B left in 2023; the text and the geos.ts comment now say 23.5°E.', checked: [read('EGNOS Service Notice 33', 'Table 1, §1'), read(SDD, '§3.3.1 Table 2'), read('EUSPA news item (25 August 2025)'), read('EGNOS Realtime page (5 October 2026)'), read('gps.gov PRN list (January 2026)', 'PRN 121, 123, 136')] },
  'egnos.geo-status-current': { verdict: 'confirmed', rationale: 'The EGNOS Realtime page, read on 5 October 2026, shows PRN 121 and 136 operational and PRN 123 in test, the configuration of Service Notices 33 and 34; Service Notice 35 (October 2025) reports an outage with full recovery and no GEO change. The text now carries the date; check it again just before a presentation.', checked: [read('EGNOS Realtime page (5 October 2026)'), read('EGNOS Service Notice 33', 'Table 1'), read('EGNOS Service Notices 34 and 35', 'p. 1')] },
  'egnos.ground-segment': { verdict: 'corrected', rationale: 'SoL SDD v3.6 §3.3.2 (read) lists the RIMS network, two MCCs, two NLES for each GEO and the EWAN, and §3.3.2.1 says the current network has 38 RIMS (38 sites in Figure 3, counted by the second reviewer). "About 40" became 38, and the ESA page, which describes the pre-2011 architecture, is no longer cited.', checked: [read(SDD, '§3.3.2, §3.3.2.1, Figure 3'), read('ESA, How does EGNOS work', 'outdated architecture')] },
  'egnos.mcc-sites': { verdict: 'confirmed', rationale: 'The Annex of Implementing Decision (EU) 2017/1406 (read on EUR-Lex) names the mission control centres at Ciampino (Italy) and Torrejón (Spain), and SoL SDD v3.6 §3.3.2 (read) confirms there are two. The ESA page describing four centres is the old architecture and is no longer cited; no later amending decision was found, though EUR-Lex was not searched exhaustively.', checked: [read('EU Implementing Decision 2017/1406', 'Annex'), read(SDD, '§3.3.2')] },
  'egnos.ground-sites': { verdict: 'corrected', rationale: 'SoL SDD v3.6 Figure 3 (read) has Toulouse, Paris, Lisbon, Madeira, the Azores, La Palma, Athens, Kuusamo and Lappeenranta, but not Alexandria (removed with SDD v3.5, per ESSP’s 2024 EWA slides) or Kourou, and no Virolahti label: EGNOS documents call the Finnish site Lappeenranta. The scenario now shows those nine RIMS, so its modelled network shrinks from 11 stations to 9. The NLES list matches the 2017 decision, and Service Notice 34 confirms new NLES units at Rambouillet and Cagliari. Re-checked on 7 October 2026 after the value changed: Figure 3 (PDF p. 20) labels Lisbon LSB, the Azores ACR and La Palma LPI (the scenario had LIS, AZO and SPC); the nine codes now match the figure and the service-area map.', on: '2026-10-07', checked: [read(SDD, '§3.3.2.1, Figure 3 (PDF p. 20, site labels)'), read('EU Implementing Decision 2017/1406', 'Annex'), read(EWA24, 'slide 2'), read('EGNOS Service Notice 34', 'p. 1'), read('NLS Finland, EGNOS RIMS station in Finland')] },
  'egnos.rims-sites': { verdict: 'corrected', rationale: 'Figure 3 of SoL SDD v3.6 (read) shows RIMS from the Canary Islands, Madeira and the Azores to Svalbard, Jan Mayen, Iceland and northern Finland, plus Agadir, Djerba, Nouakchott, Gölbaşı, Haifa, Hartebeesthoek and Moncton. Egypt and French Guiana are no longer in the network; the text now names the regions of Figure 3 (Nouakchott is West Africa). Haifa’s status should be confirmed with ESSP (Service Notice 29).', checked: [read(SDD, '§3.3.2.1, Figure 3'), read('EU Implementing Decision 2017/1406', 'Annex'), read(EWA24, 'slide 2'), read('EGNOS Service Notice 29', 'p. 1')] },
  'egnos.nles-sites': { verdict: 'confirmed', rationale: 'SoL SDD v3.6 §3.3.2.3 (read): the NLES are two for each GEO, one active and one back-up, and transmit the messages to the GEOs; the 2017 decision (read) lists the sites. The SDD replaces the old ESA page as the primary reference.', checked: [read(SDD, '§3.3.2.3'), read('EU Implementing Decision 2017/1406', 'Annex')] },
  'egnos.lpv200': { verdict: 'confirmed', rationale: 'SoL SDD v3.6 §3.2.1 (read): LPV-200 was declared with SDD v3.0 in September 2015, supporting RNP APCH down to LPV minima as low as 200 ft (Category I, VAL 35 m).', checked: [read(SDD, '§3.2.1; document change record v3.0')] },
  'egnos.sol-free': { verdict: 'confirmed', rationale: 'SoL SDD v3.6 §1 (read) says the SoL service is provided openly and is freely accessible without any direct charge. Operational use still needs authorisation and, for an ANSP, an EWA (§3.4.3), which the note now says so that "free" is not read as "no agreement needed".', checked: [read(SDD, '§1; §3.4.3')] },
  'egnos.v3-dfmc': { verdict: 'corrected', rationale: 'SoL SDD v3.6 §1 (read) confirms that EGNOS today augments GPS L1 C/A and will augment GPS and Galileo on L1 and L5. The EUSPA Industry Days 2026 roadmaps (read, as images) start EGNOS v3 operations just after 2030 and place the DFMC service after GPS L5 full operational capability, so "around 2028" was out of date; the text says "early 2030s", the precision a bar chart allows.', checked: [read('EUSPA Industry Days 2026 deck', 'infrastructure and services roadmaps, V3 development'), read(SDD, '§1; §4.1.1 note 14'), known(D9849_5, '§4.3.4.5')] },
  'egnos.fas-provider-id': { verdict: 'confirmed', rationale: 'The EUROCONTROL FAS Data Block Tool (read) lists the provider IDs 0 WAAS, 1 EGNOS, 2 MSAS, 3 GAGAN, 4 SDCM, 5 BDSBAS, 6 KASS, 7 A-SBAS, 8–13 spare, 14 GBAS only and 15 any SBAS, citing DO-229D Appendix D and Annex 10 App B; the code’s 1 matches.', checked: [read(FASDB, 'valid field types table'), known(A10, 'Appendix B, SBAS provider IDs')] },
  'essp.notam-proposal': { verdict: 'corrected', rationale: 'SoL SDD v3.6 §3.4.4 (read) describes the service: ESSP predicts service-level outages at given locations, formats NOTAM proposals in ICAO format following the European Concept for GNSS NOTAM, and sends them by AFTN to the NOTAM offices, which validate and publish them. The SDD does not limit it to APV-I, so the text now says "an EGNOS service level"; the page’s APV-I-only proposals are labelled a simplification.', checked: [read(SDD, '§3.4.4, §3.4.3'), read(EWA24, 'slide 12'), known('ESSP EGNOS Service Provision Yearly Report')] },
  'essp.notam-format': { verdict: 'illustrative', rationale: 'The SDD (§3.4.4, read) confirms that proposals use an ICAO format following the European Concept for GNSS NOTAM, and items A, B, C and E are the right ICAO items. The page says the item E wording is illustrative and the Q line and calendar date are left out, so learners will not take it for a real ESSP proposal.', checked: [read(SDD, '§3.4.4'), known('ESSP EGNOS Service Provision Yearly Report')] },
  'essp.forecast-model': { verdict: 'illustrative', rationale: 'The page forecasts with its own SBAS model and says that a real prediction uses the almanac, planned outages and the service volume model. Its split matches SDD §3.4.4 (read): scheduled events are notified at least 72 h ahead and unscheduled ones within 2 h after they occur, not predicted. The service.ts comment that listed a lost GEO among the forecast conditions has been fixed.', checked: [read(SDD, '§3.4.4'), known(D9849_5, '§4.3.3.4.1')] },
  'essp.ewa': { verdict: 'corrected', rationale: 'ESSP’s March 2024 EWA presentation (read) gives 85 EWAs in force (ATC 46, AFIS 25, air operators 7, military 5, aerodromes 2) and 954 EGNOS-based procedures serving 523 airports, and SDD §3.4.3 (read) says an EWA is required between ESSP and the ANSP. "46 with ANSPs" became "46 with ATC providers", "first step" became "must sign", and the page now shows the 523 airports. The figures are two and a half years old; ESSP can give current ones.', checked: [read(EWA24, 'EWA breakdown and procedures slides'), read(SDD, '§3.4.3')] },
  'replay.recording': { verdict: 'confirmed', rationale: 'The bundled file has 900 EMS-format lines, all PRN 124, from 15:00:00 to 15:15:00 on 29 March 2011 (one second missing), each starting with an SBAS preamble, and the decoder tests show every message passes CRC-24Q. SourceForge describes libegnos as the Linux/UNIX port of the EGNOS SDK under the EUPL. That the data came from ESA’s EMS, and that its time tags are GPS time, rest on the toolkit rather than a document read.', checked: [read('EGNOS Toolkit (SourceForge page and bundled file)'), known('ESA EMS User Interface Document')] },
  'replay.decoder-check': { verdict: 'confirmed', rationale: 'tests/essp/replay.test.ts (run: 10 of 10 pass) checks every message’s CRC over the 8+6+212-bit layout, and that the PRN mask, the fast corrections with their UDREI and the IGP delays with their GIVEI equal RTKLIB’s at four checkpoints. The claim holds for those message contents; Types 7, 9, 10, 12, 17, 25 and 27 are not compared.', checked: [read('tests/essp/replay.test.ts (run)'), known(RTKLIB, 'via the test fixture'), known(DO229, 'Appendix A')] },
  'scenario.essp-procedure': { verdict: 'illustrative', rationale: 'The page labels the RNP RWY 04L procedure, its channel (40642, inside the SBAS range) and its FAS data as an example, not the published procedure, and 200 ft is a valid LPV-200 floor (SDD §3.2.1, read). The real Nice LPV minima are probably higher because of terrain, which the label covers; it should stay visible wherever the channel and FAS block appear.', checked: [read(SDD, '§3.2.1'), known('AIP France', 'AD 2 LFMN')] },
  'scenario.essp-terrain': { verdict: 'illustrative', rationale: 'The summit heights agree with commonly published elevations (Mont Ventoux about 1910 m, Mont Aigoual 1567 m, Pic de Nore 1211 m), from expertise, and the page labels the terrain as approximate scenery. Natural Earth does not supply summit heights, so an IGN map would be the better reference for them.', checked: [known('Natural Earth')] },
  'scenario.msas': { verdict: 'confirmed', rationale: 'The gps.gov PRN list (January 2026, read) gives PRN 137 MSAS (QZS-3) at 127°E and PRN 129 MSAS (QZS-6) at 90.5°E, matching the bound values. The ground sites and the "MSAS v3" label rest on the JCAB EGNOS Workshop 2025 slides, which were not re-read; a JCAB reviewer should confirm the naming.', checked: [read('gps.gov PRN list (January 2026)', 'PRN 129, 137'), known('JCAB, EGNOS Workshop 2025', 'slides 3–6')] },
  'scenario.indonesia-provider-id': { verdict: 'illustrative', rationale: 'The FAS data block tool (read) confirms that the provider ID is a number (0–7 assigned, 8–13 spare, 14 GBAS only, 15 any SBAS). A hypothetical Indonesian SBAS has none, the scenario is labelled a what-if, and showing a name instead is a fair teaching choice; a real block could carry only an assigned ID or 15.', checked: [read(FASDB, 'valid field types table'), known(DO229, 'Appendix D')] },
  'data.coastlines': { verdict: 'confirmed', rationale: 'scripts/geo/build-coast.mjs (read) builds the coastlines from Natural Earth 1:10m, 1:50m and 1:110m land polygons, clipped and simplified, as the claim says, and docs/THIRD_PARTY.md records Natural Earth as public domain. The ESSP-SAS globe uses 1:50m over Europe on top of the 1:110m world.', checked: [read('scripts/geo/build-coast.mjs'), known('Natural Earth land polygons')] },
}

/** The AI check of a claim, if it has one. */
export function aiCheckFor(id: string): AiCheck | undefined {
  const e = ENTRIES[id]
  return e && { model: MODEL, on: ON, ...e }
}

/** Every claim id the AI check covers (a test checks each one exists). */
export const AI_CHECKED_IDS: readonly string[] = Object.keys(ENTRIES)
