/** Claims about EGNOS and ESSP (the ESSP-SAS scenario), and the data both scenarios rest on. */
import { GEO_SATS } from '@/core/orbits'
import { DEPARTURE, DESTINATION, STATIONS } from '@/core/region'
import { makeFasDataBlock } from '@/core/approach'
import { EWA_FACTS } from '@/scenarios/essp/provision'
import type { Claim } from './types'

const ESSP = ['essp'] as const
const IDN = ['indonesia'] as const

export const EGNOS_CLAIMS: readonly Claim[] = [
  {
    id: 'essp.provider',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'ESSP (European Satellite Services Provider) is the EGNOS service provider for the Open Service and the Safety-of-Life service, under an up-to-ten-year contract with EUSPA signed in July 2022; EUSPA said in 2022 that it was taking over provision of the EGNOS Data Access Service (EDAS).',
    refs: [{ source: 'euspa-egnos-ws2022', section: 'slide "New EGNOS Service Provision Phase"' }, { source: 'euspa-essp-contract' }, { source: 'egnos-sol-sdd', section: '§3.4.1' }],
    status: 'sourced',
  },
  {
    id: 'egnos.geos',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'EGNOS broadcasts its Safety-of-Life signal from GEO-1, SES-5 at 5°E (PRN 136), and GEO-3, Eutelsat 5 West B at 5°W (PRN 121, operational since 25 August 2025). GEO-2, ASTRA 5B at 23.5°E (PRN 123), moved to test on 5 September 2025.',
    refs: [{ source: 'euspa-geo3-2025' }, { source: 'egnos-service-notice-33', section: 'Table 1' }, { source: 'egnos-sol-sdd', section: '§3.3.1 Table 2' }, { source: 'egnos-realtime' }, { source: 'gps-gov-prn' }],
    note: 'The gps.gov PRN list (January 2026) still gives ASTRA 5B at 31.5°E, its slot before 2023; the operator’s documents give 23.5°E.',
    status: 'sourced',
    value: [136, 5, 121, -5],
    unit: 'PRN, degrees east',
    actual: () => GEO_SATS.flatMap((g) => [g.prn ?? 0, g.lonDeg ?? 0]),
    code: 'src/scenarios/essp/geos.ts',
  },
  {
    id: 'egnos.geo-status-current',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'Which EGNOS GEO is operational changes by service notice; the status shown is that of the September 2025 notices (Service Notices 33 and 34), still current on 5 October 2026 (EGNOS user support, Realtime).',
    refs: [{ source: 'egnos-realtime' }, { source: 'egnos-service-notice-33' }, { source: 'egnos-service-notice-34' }, { source: 'egnos-service-notice-35' }],
    note: 'Check again just before an ESSP presentation.',
    status: 'to-confirm',
    code: 'src/scenarios/essp/geos.ts',
    todo: 'EGNOS GEO status changes by service notice',
  },
  {
    id: 'egnos.ground-segment',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The EGNOS ground segment: 38 Ranging and Integrity Monitoring Stations (RIMS), two Mission Control Centres (MCC), two Navigation Land Earth Stations (NLES) for each GEO that uplink to the GEOs, and the EGNOS Wide Area Network (EWAN) (SoL SDD v3.6 §3.3.2).',
    refs: [{ source: 'egnos-sol-sdd', section: '§3.3.2, §3.3.2.1, Figure 3' }],
    status: 'sourced',
  },
  {
    id: 'egnos.mcc-sites',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The two EGNOS mission control centres are at Torrejón (Spain) and Ciampino (Italy).',
    refs: [{ source: 'eu-decision-2017-1406', section: 'Annex' }, { source: 'egnos-sol-sdd', section: '§3.3.2' }],
    status: 'sourced',
    value: 'Ciampino,Torrejón',
    actual: () =>
      STATIONS.filter((s) => s.kind === 'mcc')
        .map((s) => s.name)
        .sort()
        .join(','),
    code: 'src/scenarios/essp/region.ts',
  },
  {
    id: 'egnos.ground-sites',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The ground sites shown: RIMS at Toulouse, Paris, Lisbon, Madeira, the Azores, La Palma, Athens, Lappeenranta and Kuusamo (sites in the 38-station network of SoL SDD v3.6, Figure 3); NLES at Aussaguel, Betzdorf, Burum, Cagliari, Fucino, Rambouillet and Redu (EU Implementing Decision 2017/1406). Only some of the sites are shown, at city level.',
    refs: [{ source: 'egnos-sol-sdd', section: '§3.3.2.1, Figure 3' }, { source: 'eu-decision-2017-1406', section: 'Annex' }, { source: 'essp-ewa-2024', section: 'slide 2 (SDD v3.5: removal of the ALY and ABS RIMS)' }, { source: 'egnos-service-notice-34' }],
    status: 'to-confirm',
    value: 'ACR,ATH,KUU,LAP,LPI,LSB,MAD,PAR,TLS',
    actual: () =>
      STATIONS.filter((s) => s.kind === 'rims')
        .map((s) => s.code)
        .sort()
        .join(','),
    code: 'src/scenarios/essp/region.ts',
    todo: 'EGNOS ground sites',
    note: 'Alexandria (removed with SDD v3.5) and Kourou (not in v3.6 Figure 3) are no longer shown; the Finnish site is Lappeenranta (LAP) in EGNOS documents, which the Finnish National Land Survey calls Virolahti. Kuusamo is already in the 2017 decision. The NLES list was not re-checked against a later decision (Service Notice 34 confirms new NLES units at Rambouillet and Cagliari). Which NLES feeds which GEO is not stated in these sources; the page draws an example pairing and says so.',
  },
  {
    id: 'egnos.rims-sites',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'EGNOS RIMS span Europe and beyond, from the Canary Islands, Madeira and the Azores to Svalbard, Iceland and northern Finland, with stations also in North and West Africa, Turkey, the eastern Mediterranean, South Africa and Canada (SoL SDD v3.6, Figure 3).',
    refs: [{ source: 'egnos-sol-sdd', section: '§3.3.2.1, Figure 3' }, { source: 'eu-decision-2017-1406', section: 'Annex' }],
    status: 'sourced',
    note: 'Service Notice 29 (October 2023) reported the Haifa RIMS temporarily out of operation; v3.6 Figure 3 still draws it. Drop "the eastern Mediterranean" if ESSP says it is out.',
  },
  { id: 'egnos.nles-sites', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'Navigation land earth stations (NLES) uplink the EGNOS messages to the GEOs; each GEO has a primary and a backup uplink.', refs: [{ source: 'egnos-sol-sdd', section: '§3.3.2.3' }, { source: 'eu-decision-2017-1406', section: 'Annex' }], status: 'sourced' },
  { id: 'egnos.lpv200', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'The EGNOS Safety-of-Life service supports approaches with vertical guidance down to LPV-200 minima.', refs: [{ source: 'egnos-sol-sdd', section: '§3.2.1' }], status: 'sourced' },
  { id: 'egnos.sol-free', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'The EGNOS Safety-of-Life service is open and free of direct charge to users.', refs: [{ source: 'egnos-sol-sdd', section: '§1' }], status: 'sourced', note: 'Operational use still needs authorisation and, for an ANSP, an EGNOS Working Agreement (§3.4.3).' },
  {
    id: 'egnos.v3-dfmc',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'EGNOS v2, in service, augments GPS on L1 only. EGNOS v3 is planned to add a dual-frequency multi-constellation (DFMC) service augmenting GPS and Galileo on L1 and L5; EUSPA’s 2026 roadmap places it in the early 2030s, after GPS L5 reaches full operational capability.',
    refs: [{ source: 'euspa-egnos-v3', section: 'EGNOS infrastructure and services roadmaps' }, { source: 'egnos-sol-sdd', section: '§1; §4.1.1 note 14' }],
    status: 'sourced',
    note: 'The roadmap gives no exact year; ask ESSP or EUSPA for the official V3.2 DFMC service date.',
  },
  {
    id: 'egnos.fas-provider-id',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'In the FAS data block, SBAS service provider 1 is EGNOS (0 WAAS, 2 MSAS, 3 GAGAN, 4 SDCM, 5 BDSBAS, 6 KASS, 7 A-SBAS; 15 any SBAS).',
    refs: [{ source: 'eurocontrol-fasdb' }, { source: 'icao-annex10', section: 'Appendix B, SBAS provider IDs' }],
    status: 'sourced',
    value: 1,
    actual: () => makeFasDataBlock().sbasProviderId ?? -1,
    code: 'src/scenarios/essp/index.ts',
  },
  {
    id: 'essp.notam-proposal',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'ESSP’s NOTAM proposal service predicts when an EGNOS service level will be unavailable at airports with EGNOS-based procedures, formats the results as proposed NOTAMs (ICAO format, European Concept for GNSS NOTAM) and sends them by AFTN to the national NOTAM offices concerned, which validate and publish them.',
    refs: [{ source: 'egnos-sol-sdd', section: '§3.4.4' }, { source: 'egnos-sp-report' }],
    status: 'sourced',
    code: 'src/core/service.ts',
    note: 'The page proposes NOTAMs for APV-I only, a simplification; whether ESSP proposes separate NOTAMs for LPV-200 is for ESSP to confirm.',
  },
  {
    id: 'essp.notam-format',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The proposed NOTAM the page writes uses the ICAO NOTAM items A (location), B and C (validity, UTC) and E (text); the wording of item E is illustrative, the Q line is left out, and the flight has no calendar date.',
    refs: [{ source: 'egnos-sol-sdd', section: '§3.4.4' }, { source: 'egnos-sp-report' }],
    status: 'to-confirm',
    code: 'src/core/service.ts',
    todo: 'NOTAM proposal item E wording',
  },
  {
    id: 'essp.forecast-model',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The page forecasts LPV availability by running its own SBAS model forward at the airport with the conditions known in advance (a storm forecast, a planned RIMS outage); sudden failures such as a lost GEO are not in a forecast.',
    refs: [{ source: 'icao-doc9849', section: '§4.3.3.4.1' }, { source: 'egnos-sol-sdd', section: '§3.4.4' }, { source: 'egnos-sp-report' }],
    status: 'sourced',
    code: 'src/core/service.ts',
    note: 'A real prediction uses the almanac, planned outages and the service volume model.',
  },
  {
    id: 'essp.ewa',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'To publish EGNOS-based (LPV) procedures, an air navigation service provider must sign an EGNOS Working Agreement (EWA) with ESSP. In March 2024, 85 EWAs were in force (46 of them with ATC providers), and 954 EGNOS-based procedures served 523 airports.',
    refs: [{ source: 'essp-ewa-2024', section: 'EWA breakdown and procedures slides' }, { source: 'egnos-sol-sdd', section: '§3.4.3' }],
    status: 'sourced',
    value: [85, 46, 954, 523],
    unit: 'EWAs, of them with ATC providers, procedures, airports (March 2024)',
    actual: () => [EWA_FACTS.ewas, EWA_FACTS.withAtc, EWA_FACTS.procedures, EWA_FACTS.airports],
    code: 'src/scenarios/essp/provision.ts',
    note: 'The other EWAs are with AFIS providers (25), military ANSPs (5), air operators (7) and aerodrome operators (2). The figures are from March 2024; ask ESSP for current ones.',
  },
  // The real signal (the replay panel).
  {
    id: 'replay.recording',
    topic: 'Real signal',
    scenarios: ESSP,
    text: 'The replayed messages are real: 15 minutes broadcast by PRN 124 on 29 March 2011 from 15:00 GPS time, recorded by ESA’s EGNOS Message Server and shipped with the EGNOS Toolkit (the Linux port of the EGNOS SDK the GSA published in 2011).',
    refs: [{ source: 'egnos-toolkit' }, { source: 'esa-ems' }],
    status: 'sourced',
    code: 'src/replay/data/NOTICE.md',
    note: 'EUPL v1.1; check the licence suits the training use before distributing. EGNOS has changed since 2011: its GEOs, RIMS network and performance.',
  },
  {
    id: 'replay.decoder-check',
    topic: 'Real signal',
    scenarios: ESSP,
    text: 'SBAS Lab decodes the messages itself (the DO-229 layout: CRC-24Q, PRN mask, fast corrections and UDREI, IGP mask, ionospheric delays and GIVEI). Every recorded message passes the CRC, and the decoded picture equals the one RTKLIB’s independent decoder builds from the same file.',
    refs: [{ source: 'rtca-do229', section: 'Appendix A' }, { source: 'rtklib' }],
    status: 'sourced',
    code: 'src/core/sbasDecode.ts',
  },
  // The data the two scenarios rest on.
  {
    id: 'scenario.essp-airports',
    topic: 'Scenario data',
    scenarios: ESSP,
    text: 'Toulouse-Blagnac runway 14L (threshold 43.6374°N 1.3576°E, 490 ft, true course 143.1°, 3000 m) and Nice Côte d’Azur runway 04L (landing threshold displaced 93 m, 11 ft, true course 45.0°, 2570 m).',
    refs: [{ source: 'ourairports' }, { source: 'aip-france', section: 'AD 2 LFBO, LFMN' }],
    status: 'to-confirm',
    value: [43.637402, 1.35762, 143.11, 45],
    actual: () => [DEPARTURE.threshold.latDeg, DEPARTURE.threshold.lonDeg, DEPARTURE.runwayCourseDeg, DESTINATION.runwayCourseDeg],
    code: 'src/scenarios/essp/region.ts',
    todo: 'LFBO 14L and LFMN 04L thresholds',
  },
  {
    id: 'scenario.essp-procedure',
    topic: 'Scenario data',
    scenarios: ESSP,
    text: 'The RNP RWY 04L approach at Nice shown here (channel, FAS data, LPV-200 minima with a 200 ft decision height) is an illustrative example, not the published procedure.',
    refs: [{ source: 'aip-france', section: 'AD 2 LFMN' }],
    status: 'to-confirm',
    code: 'src/scenarios/essp/index.ts',
    todo: 'channel number and FAS data of the RNP RWY 04L approach at Nice are illustrative',
  },
  {
    id: 'scenario.essp-terrain',
    topic: 'Scenario data',
    scenarios: ESSP,
    text: 'The summits drawn between Toulouse and Nice (Mont Ventoux, Mont Aigoual and others) stand at approximate positions and heights; the terrain is illustrative scenery.',
    refs: [{ source: 'natural-earth' }],
    status: 'to-confirm',
    code: 'src/scenarios/essp/terrain.ts',
    todo: 'summit positions and heights are approximate',
  },
  {
    id: 'scenario.indonesia-airports',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'Jakarta Soekarno-Hatta runway 07R and Bali I Gusti Ngurah Rai runway 09: threshold positions, true courses, lengths and elevations from aviation databases that reproduce AIP Indonesia AD 2.',
    refs: [{ source: 'aip-indonesia', section: 'AD 2 WIII, WADD' }, { source: 'ourairports' }],
    status: 'to-confirm',
    code: 'src/scenarios/indonesia/region.ts',
    todo: 'runway threshold coordinates, true courses, lengths and elevations',
  },
  {
    id: 'scenario.indonesia-fir',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'The controller hand-off on the route (Jakarta FIR to Ujung Pandang FIR, Makassar) is described in general terms.',
    refs: [{ source: 'aip-indonesia', section: 'ENR' }],
    status: 'to-confirm',
    code: 'src/scenarios/indonesia/narration.ts',
    todo: 'the controller hand-off',
  },
  {
    id: 'scenario.msas',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'MSAS v3: GEOs QZS-3 at 127°E (PRN 137) and QZS-6 at 90.5°E (PRN 129); two MCS (Hitachi-ota, Kobe); uplinks at Hitachi-ota, Tanegashima and Miyakojima; each PRN has its own uplink.',
    refs: [{ source: 'jcab-ews2025', section: 'slides 3–6' }, { source: 'icao-apac-ip15' }, { source: 'gps-gov-prn' }],
    status: 'sourced',
    value: [137, 127, 129, 90.5],
    actual: () => GEO_SATS.flatMap((g) => [g.prn ?? 0, g.lonDeg ?? 0]),
    code: 'src/scenarios/indonesia/geos.ts',
  },
  {
    id: 'scenario.qzs6-status',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'QZS-6 (PRN 129), launched on 2 February 2025, was under test in late 2025; its SBAS service date and the L5 (DFMC) broadcast of QZS-3 and QZS-6 are to confirm.',
    refs: [{ source: 'jcab-ews2025' }],
    status: 'to-confirm',
    code: 'src/scenarios/indonesia/geos.ts',
    todo: 'QZS-6 (PRN 129) was launched on 2 Feb 2025',
  },
  {
    id: 'scenario.indonesia-provider-id',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'The hypothetical Indonesian SBAS has no SBAS service provider ID, so its FAS data block carries a name instead of the number a real block would.',
    refs: [{ source: 'rtca-do229' }, { source: 'eurocontrol-fasdb' }],
    status: 'to-confirm',
    code: 'src/core/approach.ts',
    todo: 'the real FAS block carries a numeric SBAS service provider ID',
  },
  { id: 'data.coastlines', topic: 'Scenario data', scenarios: ['indonesia', 'essp'], text: 'Coastlines come from Natural Earth land polygons (1:10m for the flight view, 1:50m for the maps, 1:110m for the globe), clipped and simplified.', refs: [{ source: 'natural-earth' }], status: 'sourced', code: 'scripts/geo/build-coast.mjs' },
]
