/** Claims about EGNOS and ESSP (the ESSP-SAS scenario), and the data both scenarios rest on. */
import { GEO_SATS } from '@/core/orbits'
import { DEPARTURE, DESTINATION, STATIONS } from '@/core/region'
import { makeFasDataBlock } from '@/core/approach'
import type { Claim } from './types'

const ESSP = ['essp'] as const
const IDN = ['indonesia'] as const

export const EGNOS_CLAIMS: readonly Claim[] = [
  {
    id: 'essp.provider',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'ESSP (European Satellite Services Provider) is the EGNOS service provider for the Open Service and the Safety-of-Life service, under a ten-year contract with EUSPA signed in July 2022; EUSPA took over the EGNOS Data Access Service (EDAS).',
    refs: [{ source: 'euspa-essp-contract' }],
    status: 'sourced',
  },
  {
    id: 'egnos.geos',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'EGNOS broadcasts its Safety-of-Life signal from GEO-1, SES-5 at 5°E (PRN 136), and GEO-3, Eutelsat 5 West B at 5°W (PRN 121, operational since 25 August 2025). GEO-2, ASTRA 5B at 31.5°E (PRN 123), moved to test on 5 September 2025.',
    refs: [{ source: 'euspa-geo3-2025' }, { source: 'egnos-service-notice-33' }, { source: 'egnos-realtime' }, { source: 'gps-gov-prn' }],
    status: 'sourced',
    value: [136, 5, 121, -5],
    unit: 'PRN, degrees east',
    actual: () => GEO_SATS.flatMap((g) => [g.prn ?? 0, g.lonDeg ?? 0]),
    code: 'src/scenarios/essp/geos.ts',
  },
  {
    id: 'egnos.geo-status-current',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'Which EGNOS GEO is operational changes by service notice; the status shown is that of the September 2025 notices, still current in early 2026.',
    refs: [{ source: 'egnos-realtime' }],
    status: 'to-confirm',
    code: 'src/scenarios/essp/geos.ts',
    todo: 'EGNOS GEO status changes by service notice',
  },
  {
    id: 'egnos.ground-segment',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The EGNOS ground segment: about 40 Ranging and Integrity Monitoring Stations (RIMS), two Mission Control Centres (MCC), Navigation Land Earth Stations (NLES) that uplink to the GEOs, and the EGNOS Wide Area Network (EWAN).',
    refs: [{ source: 'egnos-sol-sdd' }, { source: 'esa-egnos' }],
    status: 'sourced',
  },
  {
    id: 'egnos.mcc-sites',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The two EGNOS mission control centres are at Torrejón (Spain) and Ciampino (Italy).',
    refs: [{ source: 'eu-decision-2017-1406' }, { source: 'esa-egnos' }],
    status: 'sourced',
    value: 'Ciampino,Torrejón',
    actual: () =>
      STATIONS.filter((s) => s.kind === 'mcc')
        .map((s) => s.name)
        .sort()
        .join(','),
    code: 'src/scenarios/essp/region.ts',
  },
  {
    id: 'egnos.ground-sites',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The ground sites shown: RIMS at Toulouse, Paris, Lisbon, Madeira, the Azores, La Palma, Athens, Alexandria, Virolahti, Kuusamo and Kourou; NLES at Aussaguel, Betzdorf, Burum, Cagliari, Fucino, Rambouillet and Redu. Only the sites named in the public sources this build could read are shown, at city level.',
    refs: [{ source: 'eu-decision-2017-1406' }, { source: 'egnos-sol-sdd' }, { source: 'esa-egnos' }],
    status: 'to-confirm',
    code: 'src/scenarios/essp/region.ts',
    todo: 'EGNOS ground sites',
    note: 'Kuusamo is new in SoL SDD v3.6. The NLES list comes from the 2017 decision and may have changed. Which NLES feeds which GEO is not stated in these sources; the page draws an example pairing and says so.',
  },
  { id: 'egnos.rims-sites', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'EGNOS RIMS span Europe and beyond, from the Canary Islands, Madeira and the Azores to Finland, Egypt and French Guiana.', refs: [{ source: 'eu-decision-2017-1406' }, { source: 'esa-egnos' }, { source: 'egnos-sol-sdd' }], status: 'sourced' },
  { id: 'egnos.nles-sites', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'Navigation land earth stations (NLES) uplink the EGNOS messages to the GEOs; each GEO has a primary and a backup uplink.', refs: [{ source: 'esa-egnos' }, { source: 'eu-decision-2017-1406' }], status: 'sourced' },
  { id: 'egnos.lpv200', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'The EGNOS Safety-of-Life service supports approaches with vertical guidance down to LPV-200 minima.', refs: [{ source: 'egnos-sol-sdd' }], status: 'sourced' },
  { id: 'egnos.sol-free', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'The EGNOS Safety-of-Life service is open and free of direct charge to users.', refs: [{ source: 'egnos-sol-sdd' }], status: 'sourced' },
  { id: 'egnos.v3-dfmc', topic: 'EGNOS and ESSP', scenarios: ESSP, text: 'EGNOS v2, in service, is single-frequency (GPS L1). EGNOS v3 is planned to bring a dual-frequency multi-constellation (DFMC) service around 2028, after GPS L5 is declared operational.', refs: [{ source: 'euspa-egnos-v3' }, { source: 'icao-doc9849', section: '§4.3.4.5' }], status: 'sourced' },
  {
    id: 'egnos.fas-provider-id',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'In the FAS data block, SBAS service provider 1 is EGNOS (0 WAAS, 2 MSAS, 3 GAGAN, 4 SDCM, 5 BDSBAS, 6 KASS, 7 A-SBAS; 15 any SBAS).',
    refs: [{ source: 'eurocontrol-fasdb' }, { source: 'icao-annex10', section: 'Appendix B, SBAS provider IDs' }],
    status: 'sourced',
    value: 1,
    actual: () => makeFasDataBlock().sbasProviderId ?? -1,
    code: 'src/scenarios/essp/index.ts',
  },
  {
    id: 'essp.notam-proposal',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'ESSP’s NOTAM proposal service predicts periods when the EGNOS APV-I service will be unavailable at airports with EGNOS procedures, formats them as proposed NOTAMs and sends them to the NOTAM offices concerned (by AFTN).',
    refs: [{ source: 'egnos-sp-report' }],
    status: 'sourced',
  },
  {
    id: 'essp.notam-format',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The proposed NOTAM the page writes uses the ICAO NOTAM items A (location), B and C (validity, UTC) and E (text); the wording of item E is illustrative, the Q line is left out, and the flight has no calendar date.',
    refs: [{ source: 'egnos-sp-report' }],
    status: 'to-confirm',
    code: 'src/core/service.ts',
    todo: 'NOTAM proposal item E wording',
  },
  {
    id: 'essp.forecast-model',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'The page forecasts LPV availability by running its own SBAS model forward at the airport with the conditions known in advance (a storm forecast, a planned RIMS outage); sudden failures such as a lost GEO are not in a forecast.',
    refs: [{ source: 'icao-doc9849', section: '§4.3.3.4.1' }, { source: 'egnos-sp-report' }],
    status: 'sourced',
    code: 'src/core/service.ts',
    note: 'A real prediction uses the almanac, planned outages and the service volume model.',
  },
  {
    id: 'essp.ewa',
    topic: 'EGNOS and ESSP',
    scenarios: ESSP,
    text: 'An air navigation service provider’s first step to publish EGNOS-based (LPV) procedures is an EGNOS Working Agreement (EWA) with ESSP. In March 2024, 85 EWAs were in force (46 with ANSPs), and 954 EGNOS-based procedures were published.',
    refs: [{ source: 'essp-ewa-2024' }],
    status: 'sourced',
    value: [85, 46, 954],
    unit: 'EWAs, of them with ANSPs, procedures (March 2024)',
  },
  // The real signal (the replay panel).
  {
    id: 'replay.recording',
    topic: 'Real signal',
    scenarios: ESSP,
    text: 'The replayed messages are real: 15 minutes broadcast by PRN 124 on 29 March 2011 from 15:00 GPS time, recorded by ESA’s EGNOS Message Server and shipped with the EGNOS Toolkit (the Linux port of the EGNOS SDK the GSA published in 2011).',
    refs: [{ source: 'egnos-toolkit' }, { source: 'esa-ems' }],
    status: 'sourced',
    code: 'src/replay/data/NOTICE.md',
    note: 'EUPL v1.1; check the licence suits the training use before distributing. EGNOS has changed since 2011: its GEOs, RIMS network and performance.',
  },
  {
    id: 'replay.decoder-check',
    topic: 'Real signal',
    scenarios: ESSP,
    text: 'SBAS Lab decodes the messages itself (the DO-229 layout: CRC-24Q, PRN mask, fast corrections and UDREI, IGP mask, ionospheric delays and GIVEI). Every recorded message passes the CRC, and the decoded picture equals the one RTKLIB’s independent decoder builds from the same file.',
    refs: [{ source: 'rtca-do229', section: 'Appendix A' }, { source: 'rtklib' }],
    status: 'sourced',
    code: 'src/core/sbasDecode.ts',
  },
  // The data the two scenarios rest on.
  {
    id: 'scenario.essp-airports',
    topic: 'Scenario data',
    scenarios: ESSP,
    text: 'Toulouse-Blagnac runway 14L (threshold 43.6374°N 1.3576°E, 490 ft, true course 143.1°, 3000 m) and Nice Côte d’Azur runway 04L (landing threshold displaced 93 m, 11 ft, true course 45.0°, 2570 m).',
    refs: [{ source: 'ourairports' }, { source: 'aip-france', section: 'AD 2 LFBO, LFMN' }],
    status: 'to-confirm',
    value: [43.637402, 1.35762, 143.11, 45],
    actual: () => [DEPARTURE.threshold.latDeg, DEPARTURE.threshold.lonDeg, DEPARTURE.runwayCourseDeg, DESTINATION.runwayCourseDeg],
    code: 'src/scenarios/essp/region.ts',
    todo: 'LFBO 14L and LFMN 04L thresholds',
  },
  {
    id: 'scenario.essp-procedure',
    topic: 'Scenario data',
    scenarios: ESSP,
    text: 'The RNP RWY 04L approach at Nice shown here (channel, FAS data, LPV-200 minima with a 200 ft decision height) is an illustrative example, not the published procedure.',
    refs: [{ source: 'aip-france', section: 'AD 2 LFMN' }],
    status: 'to-confirm',
    code: 'src/scenarios/essp/index.ts',
    todo: 'channel number and FAS data of the RNP RWY 04L approach at Nice are illustrative',
  },
  {
    id: 'scenario.essp-terrain',
    topic: 'Scenario data',
    scenarios: ESSP,
    text: 'The summits drawn between Toulouse and Nice (Mont Ventoux, Mont Aigoual and others) stand at approximate positions and heights; the terrain is illustrative scenery.',
    refs: [{ source: 'natural-earth' }],
    status: 'to-confirm',
    code: 'src/scenarios/essp/terrain.ts',
    todo: 'summit positions and heights are approximate',
  },
  {
    id: 'scenario.indonesia-airports',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'Jakarta Soekarno-Hatta runway 07R and Bali I Gusti Ngurah Rai runway 09: threshold positions, true courses, lengths and elevations from aviation databases that reproduce AIP Indonesia AD 2.',
    refs: [{ source: 'aip-indonesia', section: 'AD 2 WIII, WADD' }, { source: 'ourairports' }],
    status: 'to-confirm',
    code: 'src/scenarios/indonesia/region.ts',
    todo: 'runway threshold coordinates, true courses, lengths and elevations',
  },
  {
    id: 'scenario.indonesia-fir',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'The controller hand-off on the route (Jakarta FIR to Ujung Pandang FIR, Makassar) is described in general terms.',
    refs: [{ source: 'aip-indonesia', section: 'ENR' }],
    status: 'to-confirm',
    code: 'src/scenarios/indonesia/narration.ts',
    todo: 'the controller hand-off',
  },
  {
    id: 'scenario.msas',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'MSAS v3: GEOs QZS-3 at 127°E (PRN 137) and QZS-6 at 90.5°E (PRN 129); two MCS (Hitachi-ota, Kobe); uplinks at Hitachi-ota, Tanegashima and Miyakojima; each PRN has its own uplink.',
    refs: [{ source: 'jcab-ews2025', section: 'slides 3–6' }, { source: 'icao-apac-ip15' }, { source: 'gps-gov-prn' }],
    status: 'sourced',
    value: [137, 127, 129, 90.5],
    actual: () => GEO_SATS.flatMap((g) => [g.prn ?? 0, g.lonDeg ?? 0]),
    code: 'src/scenarios/indonesia/geos.ts',
  },
  {
    id: 'scenario.qzs6-status',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'QZS-6 (PRN 129), launched on 2 February 2025, was under test in late 2025; its SBAS service date and the L5 (DFMC) broadcast of QZS-3 and QZS-6 are to confirm.',
    refs: [{ source: 'jcab-ews2025' }],
    status: 'to-confirm',
    code: 'src/scenarios/indonesia/geos.ts',
    todo: 'QZS-6 (PRN 129) was launched on 2 Feb 2025',
  },
  {
    id: 'scenario.indonesia-provider-id',
    topic: 'Scenario data',
    scenarios: IDN,
    text: 'The hypothetical Indonesian SBAS has no SBAS service provider ID, so its FAS data block carries a name instead of the number a real block would.',
    refs: [{ source: 'rtca-do229' }, { source: 'eurocontrol-fasdb' }],
    status: 'to-confirm',
    code: 'src/core/approach.ts',
    todo: 'the real FAS block carries a numeric SBAS service provider ID',
  },
  { id: 'data.coastlines', topic: 'Scenario data', scenarios: ['indonesia', 'essp'], text: 'Coastlines come from Natural Earth land polygons (1:10m for the flight view, 1:50m for the maps, 1:110m for the globe), clipped and simplified.', refs: [{ source: 'natural-earth' }], status: 'sourced', code: 'scripts/geo/build-coast.mjs' },
]
