/** Claims about GPS and positioning, shared by both scenarios. */
import { C_M_S, GPS_L1_HZ, GPS_L5_HZ, GPS_MU_M3_S2, WGS84_A_M, WGS84_F, WGS84_OMEGA_E_RAD_S } from '@/core/units'
import { GPS_ALTITUDE_M, GPS_INCLINATION_DEG, GPS_PLANES, GPS_SLOTS_PER_PLANE } from '@/core/orbits'
import { SIGMA_CLOCK_M, SIGMA_ORBIT_M, SIGMA_NOISE_M, SIGMA_TROPO_VERTICAL_M } from '@/core/errors'
import type { Claim } from './types'

const BOTH = ['indonesia', 'essp'] as const

export const GNSS_CLAIMS: readonly Claim[] = [
  {
    id: 'gnss.four-satellites',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'A receiver needs at least four pseudo-ranges: three for its position and one for its clock. The geometry of the satellites (the DOP) sets how range errors grow into position errors.',
    refs: [{ source: 'icao-doc9849', section: '§3.1' }],
    status: 'sourced',
    code: 'src/core/receiver.ts',
  },
  {
    id: 'gnss.constellation',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The GPS nominal constellation: 24 satellites in six orbital planes, about 20 200 km high, inclined 55°, one orbit in about 12 hours.',
    refs: [{ source: 'icao-doc9849', section: '§3.2.2' }],
    status: 'sourced',
    value: [24, 6, 20_200, 55],
    unit: 'satellites, planes, km, degrees',
    actual: () => [GPS_PLANES * GPS_SLOTS_PER_PLANE, GPS_PLANES, GPS_ALTITUDE_M / 1000, GPS_INCLINATION_DEG],
    code: 'src/core/orbits.ts',
  },
  {
    id: 'gnss.slot-phasing',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The model spaces the 24 satellites evenly (a Walker 24/6/1 pattern); the real slots are not evenly spaced.',
    refs: [{ source: 'is-gps-200' }],
    status: 'to-confirm',
    code: 'src/core/orbits.ts',
    todo: 'real GPS slot phasing is uneven',
    note: 'A simplification the page keeps; it changes the geometry, not the principles.',
  },
  {
    id: 'gnss.l5-everywhere',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The model lets every GPS satellite broadcast L5; not every GPS satellite does today.',
    refs: [{ source: 'icao-doc9849', section: '§3.2.4' }],
    status: 'to-confirm',
    code: 'src/core/orbits.ts',
    todo: 'not every GPS satellite broadcasts L5 today',
  },
  {
    id: 'gnss.frequencies',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'GPS civil signals: L1 at 1575.42 MHz and L5 at 1176.45 MHz; all GPS satellites share each frequency (CDMA).',
    refs: [{ source: 'icao-doc9849', section: '§3.2.4' }],
    status: 'sourced',
    value: [1575.42e6, 1176.45e6],
    unit: 'Hz',
    actual: () => [GPS_L1_HZ, GPS_L5_HZ],
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.speed-of-light',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The speed of light is 299 792 458 m/s (exact, by definition of the metre).',
    refs: [{ source: 'is-gps-200' }],
    status: 'sourced',
    value: 299_792_458,
    unit: 'm/s',
    actual: () => C_M_S,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.wgs84',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'WGS-84: semi-major axis 6 378 137.0 m, flattening 1/298.257223563.',
    refs: [{ source: 'nima-tr8350' }],
    status: 'sourced',
    value: [6_378_137.0, 298.257223563],
    actual: () => [WGS84_A_M, 1 / WGS84_F],
    tolerance: 1e-12,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.earth-rotation',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The Earth rotates at 7.292115 × 10⁻⁵ rad/s (WGS-84; IS-GPS-200 uses 7.2921151467 × 10⁻⁵ rad/s). The model uses the WGS-84 value; which the orbits should use is to confirm.',
    refs: [{ source: 'nima-tr8350' }, { source: 'is-gps-200' }],
    status: 'to-confirm',
    value: 7.292115e-5,
    unit: 'rad/s',
    actual: () => WGS84_OMEGA_E_RAD_S,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.mu',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The Earth’s gravitational constant used for GPS orbits: 3.986005 × 10¹⁴ m³/s².',
    refs: [{ source: 'is-gps-200' }],
    status: 'sourced',
    value: 3.986005e14,
    unit: 'm³/s²',
    actual: () => GPS_MU_M3_S2,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.errors',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'A range is wrong because of the satellite clock, the orbit, the ionosphere (usually the largest), the troposphere, multipath and receiver noise. SBAS corrects the first three for its region; the receiver models the troposphere; multipath and noise stay.',
    refs: [
      { source: 'icao-doc9849', section: '§4.3.1.1' },
      { source: 'icao-doc9849', section: '§5.2.1' },
    ],
    status: 'sourced',
    code: 'src/core/errors.ts',
  },
  {
    id: 'gnss.error-sizes',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'Illustrative 1σ sizes of the GPS broadcast clock (1.1 m) and orbit (0.8 m) errors along the line of sight.',
    refs: [{ source: 'is-gps-200' }],
    status: 'to-confirm',
    value: [1.1, 0.8],
    unit: 'm',
    actual: () => [SIGMA_CLOCK_M, SIGMA_ORBIT_M],
    code: 'src/core/errors.ts',
    todo: 'illustrative sizes of the GPS broadcast clock and orbit errors',
  },
  {
    id: 'gnss.troposphere-model',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The receiver’s tropospheric model: mapping m(E) = 1.001 / √(0.002001 + sin²E), residual σ of 0.12 m at the zenith.',
    refs: [{ source: 'rtca-do229', section: 'Appendix A' }],
    status: 'to-confirm',
    value: 0.12,
    unit: 'm',
    actual: () => SIGMA_TROPO_VERTICAL_M,
    code: 'src/core/errors.ts',
    todo: 'DO-229 Appendix A tropospheric model',
  },
  {
    id: 'gnss.airborne-multipath',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'Airborne multipath σ = 0.13 + 0.53·e^(−θ/10°) m and receiver noise σ = 0.36 m (an AAD-A-like receiver).',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    value: 0.36,
    unit: 'm',
    actual: () => SIGMA_NOISE_M,
    code: 'src/core/errors.ts',
    todo: 'DO-229 airborne multipath model',
  },
]
