/** Claims about GPS and positioning, shared by both scenarios. */
import { C_M_S, GPS_L1_HZ, GPS_L5_HZ, GPS_MU_M3_S2, WGS84_A_M, WGS84_F, WGS84_OMEGA_E_RAD_S } from '@/core/units'
import { GEO_ALTITUDE_M, GPS_ALTITUDE_M, GPS_INCLINATION_DEG, GPS_PLANES, GPS_SLOTS_PER_PLANE } from '@/core/orbits'
import { SIGMA_CLOCK_M, SIGMA_ORBIT_M, SIGMA_NOISE_M, SIGMA_TROPO_VERTICAL_M } from '@/core/errors'
import type { Claim } from './types'

const BOTH = ['indonesia', 'essp'] as const

export const GNSS_CLAIMS: readonly Claim[] = [
  {
    id: 'gnss.four-satellites',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'A receiver needs at least four pseudo-ranges: three for its position and one for its clock. The geometry of the satellites (the DOP) sets how range errors grow into position errors.',
    refs: [{ source: 'icao-doc9849', section: '§3.1' }],
    status: 'sourced',
    code: 'src/core/receiver.ts',
  },
  {
    id: 'gnss.constellation',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The GPS nominal constellation: 24 satellites in six orbital planes, about 20 200 km high, inclined 55°, one orbit in about 12 hours.',
    refs: [{ source: 'icao-doc9849', section: '§3.2.2' }, { source: 'gps-sps-ps-2020', section: '§3.2, Tables 3.2-1 and 3.2-3' }],
    status: 'sourced',
    value: [24, 6, 20_200, 55],
    unit: 'satellites, planes, km, degrees',
    actual: () => [GPS_PLANES * GPS_SLOTS_PER_PLANE, GPS_PLANES, GPS_ALTITUDE_M / 1000, GPS_INCLINATION_DEG],
    code: 'src/core/orbits.ts',
  },
  {
    id: 'gnss.geo-altitude',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'A geostationary (GEO) satellite flies 35 786 km above the equator, where one orbit takes exactly as long as one turn of the Earth, so it stays over the same spot. The model computes the height from the Earth’s gravitational constant and rotation rate; the GPS SPS Performance Standard rounds it to about 36 000 km.',
    refs: [{ source: 'gps-sps-ps-2020', section: 'Appendix A.3.3.3 (space service volume)' }, { source: 'is-gps-200', section: 'Table 20-IV (μ)' }, { source: 'nima-tr8350', section: 'Table 3.1 (ω)' }],
    status: 'sourced',
    value: 35_786,
    unit: 'km',
    tolerance: 1e-5,
    actual: () => GEO_ALTITUDE_M / 1000,
    code: 'src/core/orbits.ts GEO_ALTITUDE_M',
  },
  {
    id: 'gnss.slot-phasing',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The model spaces the 24 satellites evenly (a Walker 24/6/1 pattern); the real slots are not evenly spaced.',
    refs: [{ source: 'gps-sps-ps-2020', section: '§3.2, Table 3.2-1' }],
    status: 'to-confirm',
    code: 'src/core/orbits.ts',
    todo: 'real GPS slot phasing is uneven',
    note: 'A simplification the page keeps; it changes the geometry, not the principles.',
  },
  {
    id: 'gnss.constellation-size',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The model flies the nominal 24 satellites; the operational GPS constellation has more (about 31 in recent years). With GPS alone, gaps in RAIM coverage are therefore more frequent in the model than in reality, so each scenario starts its constellation where its approach has typical geometry: RAIM supports LNAV, as it does on almost every real approach.',
    refs: [
      { source: 'icao-doc9849', section: '§3.2.2' },
      { source: 'icao-doc9849', section: '§4.3.4.3' },
    ],
    status: 'to-confirm',
    code: 'src/core/orbits.ts',
    todo: 'the operational constellation has about 31 satellites',
    note: 'Modelling the operational constellation would be more faithful; it would change the recorded AirNav Indonesia results (tests/golden).',
  },
  {
    id: 'gnss.l5-everywhere',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The model lets every GPS satellite broadcast L5; not every GPS satellite does today.',
    refs: [{ source: 'icao-doc9849', section: '§3.2.4' }],
    status: 'to-confirm',
    code: 'src/core/orbits.ts',
    todo: 'not every GPS satellite broadcasts L5 today',
    note: 'GPS L5 is broadcast only by Block IIF and later satellites (IS-GPS-200N §6.2.5) and is not yet declared operational for safety-of-life use; confirm its status on gps.gov before a presentation.',
  },
  {
    id: 'gnss.frequencies',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'GPS civil signals: L1 at 1575.42 MHz and L5 at 1176.45 MHz; all GPS satellites share each frequency (CDMA).',
    refs: [{ source: 'icao-doc9849', section: '§3.2.4' }],
    status: 'sourced',
    value: [1575.42e6, 1176.45e6],
    unit: 'Hz',
    actual: () => [GPS_L1_HZ, GPS_L5_HZ],
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.speed-of-light',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The speed of light is 299 792 458 m/s (exact, by definition of the metre).',
    refs: [{ source: 'is-gps-200' }],
    status: 'sourced',
    value: 299_792_458,
    unit: 'm/s',
    actual: () => C_M_S,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.wgs84',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'WGS-84: semi-major axis 6 378 137.0 m, flattening 1/298.257223563.',
    refs: [{ source: 'nima-tr8350' }],
    status: 'sourced',
    value: [6_378_137.0, 298.257223563],
    actual: () => [WGS84_A_M, 1 / WGS84_F],
    tolerance: 1e-12,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.earth-rotation',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The Earth rotates at 7.292115 × 10⁻⁵ rad/s (WGS-84), the value the model uses. GPS receivers use the IS-GPS-200 value, 7.2921151467 × 10⁻⁵ rad/s, when they compute positions from the broadcast ephemeris; for the model’s idealised orbits the difference is small: about 0.6 m in the GEO orbit radius and at most 0.14 m per hour of the journey in a GPS satellite’s position, far below the range errors the page shows.',
    refs: [{ source: 'nima-tr8350' }, { source: 'is-gps-200' }],
    status: 'to-confirm',
    value: 7.292115e-5,
    unit: 'rad/s',
    actual: () => WGS84_OMEGA_E_RAD_S,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.mu',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The Earth’s gravitational constant used for GPS orbits: 3.986005 × 10¹⁴ m³/s².',
    refs: [{ source: 'is-gps-200' }],
    status: 'sourced',
    value: 3.986005e14,
    unit: 'm³/s²',
    actual: () => GPS_MU_M3_S2,
    code: 'src/core/units.ts',
  },
  {
    id: 'gnss.errors',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'A range is wrong because of the satellite clock, the orbit, the ionosphere (usually the largest), the troposphere, multipath and receiver noise. SBAS corrects the first three for its region; the receiver models the troposphere; multipath and noise stay.',
    refs: [
      { source: 'icao-doc9849', section: '§4.3.1.1' },
      { source: 'icao-doc9849', section: '§5.2.1' },
    ],
    status: 'sourced',
    code: 'src/core/errors.ts',
  },
  {
    id: 'gnss.error-sizes',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'Illustrative 1σ sizes of the GPS broadcast clock (1.1 m) and orbit (0.8 m) errors along the line of sight.',
    refs: [{ source: 'gps-sps-ps-2020', section: '§3.4.1, Table 3.4-1' }],
    status: 'to-confirm',
    value: [1.1, 0.8],
    unit: 'm',
    actual: () => [SIGMA_CLOCK_M, SIGMA_ORBIT_M],
    code: 'src/core/errors.ts',
    todo: 'illustrative sizes of the GPS broadcast clock and orbit errors',
    note: 'The truth is drawn at about 0.95 m 1σ (about 1.9 m 95 %), consistent with the SPS PS commitment of 2.0 m 95 % global average URE for the ensemble of constellation slots (7.0 m 95 % per satellite); the split between clock and orbit is illustrative.',
  },
  {
    id: 'gnss.troposphere-model',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'The receiver’s tropospheric model: mapping m(E) = 1.001 / √(0.002001 + sin²E), residual σ of 0.12 m at the zenith.',
    refs: [{ source: 'rtca-do229', section: 'Appendix A' }],
    status: 'to-confirm',
    value: 0.12,
    unit: 'm',
    actual: () => SIGMA_TROPO_VERTICAL_M,
    code: 'src/core/errors.ts',
    todo: 'DO-229 Appendix A tropospheric model',
  },
  {
    id: 'gnss.airborne-multipath',
    topic: 'GNSS',
    scenarios: BOTH,
    text: 'Airborne multipath σ = 0.13 + 0.53·e^(−θ/10°) m (the standard airframe multipath model) and receiver noise σ = 0.36 m, the largest the SBAS receiver may have for a GPS signal at minimum received power (0.15 m at maximum power).',
    refs: [
      { source: 'icao-annex10', section: 'Appendix B 3.5.8.4.1 (receiver noise), 3.6.5.5.1.1.2 (multipath, referenced for SBAS by the Note to 3.5.8.4.2); Attachment D 6.3.9' },
      { source: 'rtca-do229' },
    ],
    status: 'to-confirm',
    value: 0.36,
    unit: 'm',
    actual: () => SIGMA_NOISE_M,
    code: 'src/core/errors.ts',
    todo: 'DO-229 airborne multipath model',
  },
]
