/** Claims about how SBAS works, shared by both scenarios. */
import { K_H_NPA, K_H_PA, K_V_PA } from '@/core/receiver'
import { MASK_DEG, UDRE_TABLE_M, UDREI_DO_NOT_USE, UDREI_NOT_FOR_LPV, UDREI_NOT_MONITORED, sigmaUdreM } from '@/core/groundSegment'
import { GIVE_TABLE_M, GIVEI_NOT_MONITORED, IGP_SPACING_DEG, IONO_SHELL_HEIGHT_M, sigmaGiveM } from '@/core/iono'
import { DFMC_MESSAGE_BITS, MESSAGE_BITS, MESSAGE_PERIOD_S, TIMEOUTS_S } from '@/core/messages'
import { APPROACH_CHANNEL, crc32q } from '@/core/approach'
import type { Claim } from './types'

const BOTH = ['indonesia', 'essp'] as const
const D9849 = (section: string) => ({ source: 'icao-doc9849' as const, section })

export const SBAS_CLAIMS: readonly Claim[] = [
  { id: 'sbas.reference-stations', topic: 'SBAS', scenarios: BOTH, text: 'Reference stations at surveyed positions over a large area monitor the satellites and send their data to master stations.', refs: [D9849('§4.3.1.1')], status: 'sourced', code: 'src/core/groundSegment.ts' },
  {
    id: 'sbas.master-corrections',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'Master stations compute clock and orbit corrections for each satellite and ionospheric delays on a grid, and bound what is left.',
    refs: [D9849('§4.3.1.1'), D9849('§4.3.1.4.2')],
    status: 'sourced',
    code: 'src/core/groundSegment.ts',
  },
  { id: 'sbas.udre-give', topic: 'SBAS', scenarios: BOTH, text: 'UDRE bounds the residual clock and orbit error of each satellite; GIVE bounds the error of each grid point’s ionospheric delay.', refs: [D9849('§4.3.1.4.2')], status: 'sourced', code: 'src/core/groundSegment.ts' },
  {
    id: 'sbas.do-not-use',
    topic: 'SBAS',
    scenarios: BOTH,
    text: '"Do Not Use" and "Not Monitored" satellites cannot be used with SBAS integrity; LP and LPV also need UDREI other than 13.',
    refs: [D9849('§4.3.1.3')],
    status: 'sourced',
    value: [13, 14, 15],
    unit: 'UDREI (not for LPV, Not Monitored, Do Not Use)',
    actual: () => [UDREI_NOT_FOR_LPV, UDREI_NOT_MONITORED, UDREI_DO_NOT_USE],
    code: 'src/core/groundSegment.ts',
  },
  {
    id: 'sbas.udre-table',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The UDREI table: UDRE 0.75, 1.0, 1.25, 1.75, 2.25, 3.0, 3.75, 4.5, 5.25, 6.0, 7.5, 15, 50 and 150 m for UDREI 0–13; 14 is Not Monitored and 15 Do Not Use.',
    refs: [{ source: 'rtca-do229', section: 'Table A-6' }, { source: 'icao-annex10', section: 'Appendix B' }],
    status: 'to-confirm',
    value: [0.75, 1.0, 1.25, 1.75, 2.25, 3.0, 3.75, 4.5, 5.25, 6.0, 7.5, 15.0, 50.0, 150.0],
    unit: 'm',
    actual: () => UDRE_TABLE_M,
    code: 'src/core/groundSegment.ts',
    todo: 'UDREI table (RTCA DO-229, Table A-6)',
  },
  {
    id: 'sbas.sigma-udre',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'σ_UDRE is taken as UDRE / 3.29 (UDRE bounds 99.9 %); DO-229 tabulates σ²_UDRE for each UDREI, and the two agree to the table’s rounding (UDREI 0: 0.0520 m²).',
    refs: [{ source: 'rtca-do229', section: 'Table A-6' }],
    status: 'to-confirm',
    value: 0.052,
    unit: 'm² (σ² at UDREI 0)',
    tolerance: 0.01,
    actual: () => sigmaUdreM(0) ** 2,
    code: 'src/core/groundSegment.ts',
    todo: 'relation of σ_UDRE to UDRE',
  },
  {
    id: 'sbas.give-table',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The GIVEI table: GIVE 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0, 3.6, 4.5, 6.0, 15 and 45 m for GIVEI 0–14; 15 is Not Monitored.',
    refs: [{ source: 'rtca-do229', section: 'Table A-17' }],
    status: 'to-confirm',
    value: [0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0, 3.6, 4.5, 6.0, 15.0, 45.0, 15],
    unit: 'm',
    actual: () => [...GIVE_TABLE_M, GIVEI_NOT_MONITORED],
    code: 'src/core/iono.ts',
    todo: 'GIVEI table (RTCA DO-229, Table A-17)',
  },
  {
    id: 'sbas.sigma-give',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'σ_GIVE is taken as GIVE / 3.29; DO-229 tabulates σ²_GIVE for each GIVEI (GIVEI 0: 0.0084 m²).',
    refs: [{ source: 'rtca-do229', section: 'Table A-17' }],
    status: 'to-confirm',
    value: 0.0084,
    unit: 'm² (σ² at GIVEI 0)',
    tolerance: 0.02,
    actual: () => sigmaGiveM(0) ** 2,
    code: 'src/core/iono.ts',
    todo: 'relation between GIVE and σ_GIVE',
  },
  {
    id: 'sbas.igp-grid',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'Ionospheric grid points are 5° apart in latitude and longitude between 55°S and 55°N.',
    refs: [{ source: 'rtca-do229', section: 'IGP bands' }],
    status: 'to-confirm',
    value: 5,
    unit: 'degrees',
    actual: () => IGP_SPACING_DEG,
    code: 'src/core/iono.ts',
    todo: '5°×5° IGP spacing',
  },
  {
    id: 'sbas.iono-shell',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The ionosphere is modelled as a thin shell 350 km above the Earth; pierce points and the obliquity factor follow from it.',
    refs: [{ source: 'rtca-do229', section: 'Appendix A' }],
    status: 'to-confirm',
    value: 350_000,
    unit: 'm',
    actual: () => IONO_SHELL_HEIGHT_M,
    code: 'src/core/iono.ts',
    todo: '350 km thin-shell height',
  },
  {
    id: 'sbas.geo-broadcast',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'Uplink stations send the messages to the SBAS GEO satellites, which rebroadcast them; a GEO stays over the equator at a fixed longitude.',
    refs: [D9849('§4.3.1.2')],
    status: 'sourced',
    code: 'src/core/orbits.ts',
  },
  {
    id: 'sbas.message-rate',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'An SBAS GEO broadcasts one 250-bit message every second (250 bit/s, 500 symbols/s after forward error correction). On L1 a message is an 8-bit preamble, a 6-bit type, 212 data bits and a 24-bit CRC.',
    refs: [{ source: 'icao-annex10', section: 'Appendix B' }, { source: 'rtca-do229' }],
    status: 'to-confirm',
    value: [250, 1, 8, 6, 212, 24],
    unit: 'bits, s, bits',
    actual: () => [MESSAGE_BITS.total, MESSAGE_PERIOD_S, MESSAGE_BITS.preamble, MESSAGE_BITS.type, MESSAGE_BITS.data, MESSAGE_BITS.crc],
    code: 'src/core/messages.ts',
    todo: '250 bit/s, 500 symbols/s after FEC',
    note: 'The recorded EGNOS messages (src/replay) confirm the L1 layout: every one passes the 24-bit CRC over this layout and starts with an 8-bit preamble.',
  },
  {
    id: 'sbas.dfmc-layout',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'A DFMC message on L5 is also 250 bits a second, but with a 4-bit preamble: 4 + 6 + 216 + 24 bits.',
    refs: [{ source: 'eurocae-ed259' }, { source: 'icao-annex10', section: 'DFMC SBAS SARPs' }],
    status: 'to-confirm',
    value: [250, 4, 6, 216, 24],
    actual: () => [DFMC_MESSAGE_BITS.total, DFMC_MESSAGE_BITS.preamble, DFMC_MESSAGE_BITS.type, DFMC_MESSAGE_BITS.data, DFMC_MESSAGE_BITS.crc],
    code: 'src/core/messages.ts',
    todo: 'DFMC L5 layout 4+6+216+24 bits',
    note: 'The 4-bit preamble is confirmed by public summaries of the DFMC SARPs; 216 data bits follow from the 250-bit total.',
  },
  {
    id: 'sbas.message-types',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The message type numbers and names (L1: 1 PRN mask, 2–5 fast corrections, 6 integrity, 7 fast-correction degradation, 9 GEO navigation, 10 degradation, 12 network time, 17 GEO almanac, 18 IGP mask, 24 mixed, 25 long-term, 26 ionospheric delays, 27/28, 63 null; DFMC: 31, 32, 34, 37, 39, 47).',
    refs: [{ source: 'rtca-do229' }, { source: 'eurocae-ed259' }, D9849('§4.3.4.2'), D9849('Appendix G 2.5')],
    status: 'to-confirm',
    code: 'src/core/messages.ts',
    todo: 'message type numbers and names other than Types 0, 27, 28',
    note: 'Doc 9849 names Types 0, 27, 28 and 32. The L1 types the replay decodes (1, 2–5, 6, 7, 9, 10, 12, 17, 18, 24, 25, 26, 27, 63) appear in the recorded EGNOS broadcast with those numbers.',
  },
  { id: 'sbas.mt0', topic: 'SBAS', scenarios: BOTH, text: 'Message Type 0 means "do not use this SBAS for safety-of-life"; Types 27 and 28 (L1) and 32 (DFMC) bound the errors away from the network.', refs: [D9849('Appendix G 2.5'), D9849('§4.3.4.2')], status: 'sourced', code: 'src/core/messages.ts' },
  {
    id: 'sbas.timeouts',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'How long received data may be used: fast corrections 12 s for approaches with vertical guidance and 18 s otherwise, long-term corrections 240 s / 360 s, the ionospheric grid 600 s.',
    refs: [{ source: 'rtca-do229', section: 'Table A-25' }, { source: 'eurocae-ed259' }],
    status: 'to-confirm',
    value: [12, 18, 240, 360, 600],
    unit: 's',
    actual: () => [TIMEOUTS_S.fastCorrections.PA, TIMEOUTS_S.fastCorrections.NPA, TIMEOUTS_S.longTerm.PA, TIMEOUTS_S.longTerm.NPA, TIMEOUTS_S.iono.PA],
    code: 'src/core/messages.ts',
    todo: 'message time-outs (RTCA DO-229, Table A-25)',
    note: '12 s / 18 s are the time-outs of the integrity (UDREI) data; the fast-correction time-out itself follows from the MT7 degradation parameters. Check which the GEO-loss behaviour should use.',
  },
  {
    id: 'sbas.alarm-latency',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The page’s detection (2.5 s) and uplink (1.2 s) latencies are illustrative; the requirement is the time to alert.',
    refs: [D9849('Table 2-1')],
    status: 'to-confirm',
    code: 'src/core/messages.ts',
    todo: 'detection and alarm latencies are illustrative',
  },
  { id: 'sbas.operations-supported', topic: 'SBAS', scenarios: BOTH, text: 'With satellite status and clock and orbit corrections, SBAS supports departure to non-precision approach; with the ionospheric grid too, approaches with vertical guidance up to Category I.', refs: [D9849('§4.3.1.5')], status: 'sourced', code: 'src/core/sbasWorld.ts' },
  {
    id: 'sbas.protection-levels',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The receiver combines UDRE, GIVE and its own error models into protection levels (HPL, VPL) and compares them with the alert limits (HAL, VAL).',
    refs: [D9849('§4.3.2.4'), D9849('§2.2.4.3')],
    status: 'sourced',
    code: 'src/core/receiver.ts',
  },
  {
    id: 'sbas.k-factors',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'HPL = K_H·d_major and VPL = K_V·d_V, with K_H = 6.0 for approaches with vertical guidance and 6.18 otherwise, and K_V = 5.33.',
    refs: [{ source: 'rtca-do229', section: 'Appendix J' }, { source: 'icao-annex10', section: 'Appendix B' }],
    status: 'to-confirm',
    value: [6.0, 6.18, 5.33],
    actual: () => [K_H_PA, K_H_NPA, K_V_PA],
    code: 'src/core/receiver.ts',
    todo: 'K factors (RTCA DO-229 / Annex 10 Appendix B)',
  },
  {
    id: 'sbas.raim',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'GPS alone uses RAIM/FDE; its detection thresholds and protection-level factors are illustrative values (false-alarm probability about 10⁻⁵).',
    refs: [D9849('§4.2')],
    status: 'to-confirm',
    code: 'src/core/receiver.ts',
    todo: 'RAIM/FDE thresholds are illustrative',
  },
  {
    id: 'sbas.mask-angle',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'Satellites below 5° elevation are not tracked, by the aircraft or by the reference stations.',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    value: 5,
    unit: 'degrees',
    actual: () => MASK_DEG,
    code: 'src/core/groundSegment.ts',
    todo: '5° mask angle',
  },
  {
    id: 'sbas.abas-iono-sigma',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'GPS alone: the σ of the broadcast-model ionospheric residual is taken as 9 m vertically at low magnetic latitudes, times the obliquity.',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    code: 'src/core/sbasWorld.ts',
    todo: 'σ of the single-frequency broadcast-model ionospheric residual',
  },
  {
    id: 'sbas.dfre',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The DFMC service’s correction bound (DFRE) is modelled with the same bound as UDRE; the DFREI table of ED-259 differs.',
    refs: [{ source: 'eurocae-ed259' }],
    status: 'to-confirm',
    code: 'src/core/sbasWorld.ts',
    todo: 'DFRE is modelled with the same bound as UDRE',
  },
  { id: 'sbas.mode-annunciation', topic: 'SBAS', scenarios: BOTH, text: 'The avionics annunciate the highest level of service the signal supports: LPV, LNAV/VNAV or LNAV.', refs: [D9849('§4.3.2.5')], status: 'sourced', code: 'src/core/sbasWorld.ts approachMode' },
  { id: 'sbas.fas-crc', topic: 'SBAS', scenarios: BOTH, text: 'The final approach segment (FAS) data block defines the LPV final approach, and a CRC protects it.', refs: [D9849('§4.3.2.7')], status: 'sourced', code: 'src/core/approach.ts' },
  {
    id: 'sbas.fas-fields',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The FAS data block’s fields (operation type, provider, airport, runway, performance designator, reference path, threshold, glide path, threshold crossing height, course width, HAL, VAL), with a typical 105 m course width at the threshold.',
    refs: [{ source: 'rtca-do229' }, { source: 'icao-annex10', section: 'Appendix B' }],
    status: 'to-confirm',
    code: 'src/core/approach.ts',
    todo: 'FAS data block field set',
  },
  {
    id: 'sbas.fas-crc32q',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The FAS data block CRC is a 32-bit CRC (CRC-32Q, polynomial 0x814141AB).',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    value: '0x814141AB',
    actual: () => `0x${(crc32q(new Uint8Array([1])) >>> 0).toString(16).toUpperCase()}`,
    code: 'src/core/approach.ts',
    todo: 'CRC-32Q, polynomial 0x814141AB',
    note: 'The CRC of the single byte 0x01 is the polynomial itself, which is how the binding reads it.',
  },
  { id: 'sbas.channel', topic: 'SBAS', scenarios: BOTH, text: 'Crews can select an SBAS approach by its five-digit channel number.', refs: [D9849('§4.3.2.9')], status: 'sourced', code: 'src/core/approach.ts' },
  {
    id: 'sbas.channel-range',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'SBAS approach channels run from 40 000 to 99 999.',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    value: 1,
    actual: () => (APPROACH_CHANNEL >= 40_000 && APPROACH_CHANNEL <= 99_999 ? 1 : 0),
    code: 'src/core/approach.ts',
    todo: 'SBAS channel number range',
  },
  {
    id: 'sbas.lpv-deviations',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'LPV deviations: lateral full scale is the course width at the threshold, splaying out (capped at 2°); vertical full scale is a quarter of the glide path angle.',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    code: 'src/core/approach.ts',
    todo: 'lateral splay (±2° cap)',
  },
  {
    id: 'sbas.decision-height',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The decision height of each scenario’s LPV procedure is illustrative: 250 ft at Bali, 200 ft for the LPV-200 at Nice.',
    refs: [D9849('§4.3.3.3')],
    status: 'to-confirm',
    code: 'src/core/approach.ts',
    todo: 'the LPV decision height is procedure-specific',
  },
  { id: 'sbas.two-geos', topic: 'SBAS', scenarios: BOTH, text: 'LNAV/VNAV, LP and LPV need the avionics to track two SBAS satellites.', refs: [D9849('§4.3.2.10')], status: 'sourced', code: 'src/core/sbasWorld.ts', note: 'The model keeps LPV with one GEO and loses it when both are lost (after the time-out). Confirm that reading.' },
  { id: 'sbas.abas-fallback', topic: 'SBAS', scenarios: BOTH, text: 'Outside SBAS service, SBAS avionics fall back to ABAS (GPS alone with RAIM) automatically.', refs: [D9849('§4.3.4.3')], status: 'sourced', code: 'src/core/sbasWorld.ts navStatus' },
  { id: 'sbas.no-airport-equipment', topic: 'SBAS', scenarios: BOTH, text: 'SBAS approaches need no dedicated equipment at the airport.', refs: [D9849('§4.3.3.1')], status: 'sourced' },
  {
    id: 'sbas.cat1-200ft',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'A 35 m VAL supports a 200 ft decision height (SBAS Category I, LPV-200); WAAS’s worst observed vertical error was 8.9 m in 1.76 billion samples.',
    refs: [D9849('§4.3.3.3')],
    status: 'sourced',
  },
]
