/** Claims about how SBAS works, shared by both scenarios. */
import { K_H_NPA, K_H_PA, K_V_PA, PBIAS } from '@/core/receiver'
import { MASK_DEG, UDRE_TABLE_M, UDREI_DO_NOT_USE, UDREI_NOT_MONITORED, sigmaUdreM, usableForPa } from '@/core/groundSegment'
import { GIVE_TABLE_M, GIVEI_NOT_MONITORED, IGP_SPACING_DEG, IONO_SHELL_HEIGHT_M, sigmaGiveM, tauVertNoSbasM } from '@/core/iono'
import { ALARM_LATENCY, DFMC_MESSAGE_BITS, MESSAGE_BITS, MESSAGE_PERIOD_S, MESSAGES_LOST_PA, TIMEOUTS_S } from '@/core/messages'
import { SCENARIOS } from '@/scenarios/active'
import { APPROACH_CHANNEL, GARP_BEYOND_FPAP_M, crc32q } from '@/core/approach'
import type { Claim } from './types'

const BOTH = ['indonesia', 'essp'] as const
const D9849 = (section: string) => ({ source: 'icao-doc9849' as const, section })
const A10 = (section: string) => ({ source: 'icao-annex10' as const, section })

export const SBAS_CLAIMS: readonly Claim[] = [
  { id: 'sbas.reference-stations', topic: 'SBAS', scenarios: BOTH, text: 'Reference stations at surveyed positions over a large area monitor the satellites and send their data to master stations.', refs: [D9849('§4.3.1.1')], status: 'sourced', code: 'src/core/groundSegment.ts' },
  {
    id: 'sbas.master-corrections',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'Master stations compute clock and orbit corrections for each satellite and ionospheric delays on a grid, and bound what is left.',
    refs: [D9849('§4.3.1.1'), D9849('§4.3.1.4.2')],
    status: 'sourced',
    code: 'src/core/groundSegment.ts',
  },
  { id: 'sbas.udre-give', topic: 'SBAS', scenarios: BOTH, text: 'UDRE bounds the residual clock and orbit error of each satellite; GIVE bounds the error of each grid point’s ionospheric delay.', refs: [D9849('§4.3.1.4.2')], status: 'sourced', code: 'src/core/groundSegment.ts' },
  {
    id: 'sbas.do-not-use',
    topic: 'SBAS',
    scenarios: BOTH,
    text: '"Do Not Use" (UDREI 15) and "Not Monitored" (UDREI 14) satellites cannot be used with SBAS integrity; for precision approach and APV (LNAV/VNAV, LPV) a satellite with UDREI 12 or 13 (UDRE 50 m or 150 m) cannot be used either.',
    refs: [A10('Appendix B 3.5.8.1.2.12'), D9849('§4.3.1.3')],
    status: 'sourced',
    value: [12, 14, 15],
    unit: 'UDREI (first not usable for precision approach and APV, Not Monitored, Do Not Use)',
    // The first UDREI the receiver rule (usableForPa) refuses for precision approach and APV.
    actual: () => [UDRE_TABLE_M.findIndex((_, u) => !usableForPa(u)), UDREI_NOT_MONITORED, UDREI_DO_NOT_USE],
    code: 'src/core/groundSegment.ts',
    note: 'Annex 10 states the rule for precision approach and APV; LP is left out until RTCA DO-229 is checked.',
  },
  {
    id: 'sbas.udre-table',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The UDREI table: UDRE 0.75, 1.0, 1.25, 1.75, 2.25, 3.0, 3.75, 4.5, 5.25, 6.0, 7.5, 15, 50 and 150 m for UDREI 0–13; 14 is Not Monitored and 15 Do Not Use.',
    refs: [{ source: 'rtca-do229', section: 'Table A-6' }, { source: 'icao-annex10', section: 'Appendix B' }],
    status: 'to-confirm',
    value: [0.75, 1.0, 1.25, 1.75, 2.25, 3.0, 3.75, 4.5, 5.25, 6.0, 7.5, 15.0, 50.0, 150.0],
    unit: 'm',
    actual: () => UDRE_TABLE_M,
    code: 'src/core/groundSegment.ts',
    todo: 'UDREI table (RTCA DO-229, Table A-6)',
  },
  {
    id: 'sbas.sigma-udre',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'σ_UDRE is taken as UDRE / 3.29 (UDRE bounds 99.9 %); DO-229 tabulates σ²_UDRE for each UDREI, and the two agree to the table’s rounding (UDREI 0: 0.0520 m²).',
    refs: [{ source: 'rtca-do229', section: 'Table A-6' }],
    status: 'to-confirm',
    value: 0.052,
    unit: 'm² (σ² at UDREI 0)',
    tolerance: 0.01,
    actual: () => sigmaUdreM(0) ** 2,
    code: 'src/core/groundSegment.ts',
    todo: 'relation of σ_UDRE to UDRE',
  },
  {
    id: 'sbas.give-table',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The GIVEI table: GIVE 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0, 3.6, 4.5, 6.0, 15 and 45 m for GIVEI 0–14; 15 is Not Monitored.',
    refs: [{ source: 'rtca-do229', section: 'Table A-17' }],
    status: 'to-confirm',
    value: [0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0, 3.6, 4.5, 6.0, 15.0, 45.0, 15],
    unit: 'm',
    actual: () => [...GIVE_TABLE_M, GIVEI_NOT_MONITORED],
    code: 'src/core/iono.ts',
    todo: 'GIVEI table (RTCA DO-229, Table A-17)',
  },
  {
    id: 'sbas.sigma-give',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'σ_GIVE is taken as GIVE / 3.29; DO-229 tabulates σ²_GIVE for each GIVEI (GIVEI 0: 0.0084 m²).',
    refs: [{ source: 'rtca-do229', section: 'Table A-17' }],
    status: 'to-confirm',
    value: 0.0084,
    unit: 'm² (σ² at GIVEI 0)',
    tolerance: 0.02,
    actual: () => sigmaGiveM(0) ** 2,
    code: 'src/core/iono.ts',
    todo: 'relation between GIVE and σ_GIVE',
  },
  {
    id: 'sbas.igp-grid',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'Ionospheric grid points are 5° apart in latitude and longitude between 55°S and 55°N.',
    refs: [{ source: 'rtca-do229', section: 'IGP bands' }],
    status: 'to-confirm',
    value: 5,
    unit: 'degrees',
    actual: () => IGP_SPACING_DEG,
    code: 'src/core/iono.ts',
    todo: '5°×5° IGP spacing',
  },
  {
    id: 'sbas.iono-shell',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The ionosphere is modelled as a thin shell 350 km above the Earth; pierce points and the obliquity factor follow from it.',
    refs: [{ source: 'rtca-do229', section: 'Appendix A' }, { source: 'egnos-sol-sdd', section: 'Appendix C.1' }],
    status: 'to-confirm',
    value: 350_000,
    unit: 'm',
    actual: () => IONO_SHELL_HEIGHT_M,
    code: 'src/core/iono.ts',
    todo: '350 km thin-shell height',
  },
  {
    id: 'sbas.geo-broadcast',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'Uplink stations send the messages to the SBAS GEO satellites, which rebroadcast them; a GEO stays over the equator at a fixed longitude.',
    refs: [D9849('§4.3.1.2')],
    status: 'sourced',
    code: 'src/core/orbits.ts',
  },
  {
    id: 'sbas.message-rate',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'An SBAS GEO broadcasts one 250-bit message every second (250 bit/s, 500 symbols/s after forward error correction). On L1 a message is an 8-bit preamble, a 6-bit type, 212 data bits and a 24-bit CRC.',
    refs: [{ source: 'icao-annex10', section: 'Appendix B' }, { source: 'egnos-sol-sdd', section: '§4.1.1' }, { source: 'rtca-do229' }],
    status: 'to-confirm',
    value: [250, 1, 8, 6, 212, 24],
    unit: 'bits, s, bits',
    actual: () => [MESSAGE_BITS.total, MESSAGE_PERIOD_S, MESSAGE_BITS.preamble, MESSAGE_BITS.type, MESSAGE_BITS.data, MESSAGE_BITS.crc],
    code: 'src/core/messages.ts',
    todo: '250 bit/s, 500 symbols/s after FEC',
    note: 'The recorded EGNOS messages (src/replay) confirm the L1 layout: every one passes the 24-bit CRC over this layout and starts with an 8-bit preamble.',
  },
  {
    id: 'sbas.dfmc-layout',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'A DFMC message on L5 is also 250 bits a second, but with a 4-bit preamble: 4 + 6 + 216 + 24 bits.',
    refs: [{ source: 'eurocae-ed259' }, { source: 'icao-annex10', section: 'DFMC SBAS SARPs' }],
    status: 'to-confirm',
    value: [250, 4, 6, 216, 24],
    actual: () => [DFMC_MESSAGE_BITS.total, DFMC_MESSAGE_BITS.preamble, DFMC_MESSAGE_BITS.type, DFMC_MESSAGE_BITS.data, DFMC_MESSAGE_BITS.crc],
    code: 'src/core/messages.ts',
    todo: 'DFMC L5 layout 4+6+216+24 bits',
    note: 'The 4-bit preamble is confirmed by public summaries of the DFMC SARPs; 216 data bits follow from the 250-bit total.',
  },
  {
    id: 'sbas.message-types',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The message type numbers and names (L1: 1 PRN mask, 2–5 fast corrections, 6 integrity, 7 fast-correction degradation, 9 GEO navigation, 10 degradation, 12 network time, 17 GEO almanac, 18 IGP mask, 24 mixed, 25 long-term, 26 ionospheric delays, 27/28, 63 null; DFMC: 31, 32, 34, 37, 39, 47).',
    refs: [{ source: 'rtca-do229' }, { source: 'eurocae-ed259' }, D9849('§4.3.4.2'), D9849('Appendix G 2.5'), { source: 'egnos-sol-sdd', section: '§4.1.2 Table 4' }, { source: 'faa-waas-ps-2008', section: 'Table 2.1-1' }],
    status: 'to-confirm',
    code: 'src/core/messages.ts',
    todo: 'message type numbers and names other than Types 0, 27, 28',
    note: 'Doc 9849 names Types 0, 27, 28 and 32. The L1 numbers and names agree with EGNOS SoL SDD v3.6 Table 4 and the WAAS PS Table 2.1-1; EGNOS broadcasts no Type 28, so the page’s L1 broadcast plan leaves it out. The recorded EGNOS broadcast (2011) contains Types 1, 2, 3, 7, 9, 10, 12, 17, 18, 24, 25, 26 and 27. The DFMC numbers (ED-259) are to confirm.',
  },
  { id: 'sbas.mt0', topic: 'SBAS', scenarios: BOTH, text: 'Message Type 0 means "do not use this SBAS for safety-of-life"; Types 27 and 28 (L1) and 32 (DFMC) bound the errors away from the network.', refs: [D9849('Appendix G 2.5'), D9849('§4.3.4.2')], status: 'sourced', code: 'src/core/messages.ts' },
  {
    id: 'sbas.timeouts',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'How long received data may be used: the integrity data (UDREI) 12 s for precision approach and APV (LNAV/VNAV, LPV) and 18 s for en route, terminal and NPA; the fast corrections themselves time out after I_fc, set by the degradation factor in Message Type 7 (12 to 120 s for approach, 18 to 180 s otherwise); long-term corrections 240 s / 360 s; the ionospheric corrections 600 s. During an approach with HAL ≤ 40 m or VAL ≤ 50 m, losing 4 successive messages invalidates all UDREI data, so LPV and LNAV/VNAV end after 4 s without a GEO signal.',
    refs: [A10('Appendix B Table B-94, Table B-95, 3.5.8.1.2.7, 3.5.8.1.2.8'), { source: 'faa-waas-pan92', section: 'Table 5-3' }, { source: 'rtca-do229', section: 'Table A-25' }, { source: 'eurocae-ed259' }],
    status: 'to-confirm',
    value: [12, 18, 240, 360, 600, 4],
    unit: 's',
    actual: () => [TIMEOUTS_S.udrei.PA, TIMEOUTS_S.udrei.NPA, TIMEOUTS_S.longTerm.PA, TIMEOUTS_S.longTerm.NPA, TIMEOUTS_S.iono.PA, MESSAGES_LOST_PA * MESSAGE_PERIOD_S],
    code: 'src/core/messages.ts',
    todo: 'message time-outs',
    note: 'The GEO-loss behaviour uses the four-lost-messages rule for vertical guidance and the 18 s UDREI time-out for en route to NPA. LP is not named in the Annex 10 columns, so it is not put in the 12 s column until DO-229 is checked. The four-messages rule (App B 3.5.8.1.2.7) is to confirm in DO-229; the WAAS PAN report gives the same time-outs as Table B-94.',
  },
  {
    id: 'sbas.alarm-latency',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The page’s detection (2.5 s) and uplink (1.2 s) latencies are illustrative; the requirement is the time to alert.',
    refs: [D9849('Table 2-1')],
    status: 'to-confirm',
    value: [2.5, 1.2],
    unit: 's (detection, uplink)',
    actual: () => [ALARM_LATENCY.detectS, ALARM_LATENCY.uplinkS],
    code: 'src/core/messages.ts',
    todo: 'detection and alarm latencies are illustrative',
  },
  { id: 'sbas.operations-supported', topic: 'SBAS', scenarios: BOTH, text: 'With satellite status and clock and orbit corrections, SBAS supports departure to non-precision approach; with the ionospheric grid too, approaches with vertical guidance up to Category I.', refs: [D9849('§4.3.1.5')], status: 'sourced', code: 'src/core/sbasWorld.ts' },
  {
    id: 'sbas.protection-levels',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The receiver combines UDRE, GIVE and its own error models into protection levels (HPL, VPL) and compares them with the alert limits (HAL, VAL). Simplified: when SBAS messages stop arriving, the page keeps the protection levels of the last messages until the time-out; a real receiver widens them as the corrections age (the degradation data of Message Types 7 and 10).',
    refs: [D9849('§4.3.2.4'), D9849('§2.2.4.3'), { source: 'egnos-sol-sdd', section: '§4.1.2 Table 4' }],
    status: 'sourced',
    code: 'src/core/receiver.ts',
    note: 'The simplification is labelled on screen in the SBAS status panel while the message age grows (page/panels.tsx StatusPanel). The degradation formulas (RTCA DO-229) were not available, so none is modelled.',
  },
  {
    id: 'sbas.k-factors',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'HPL = K_H·d_major and VPL = K_V·d_V, with K_H = 6.0 for approaches with vertical guidance and 6.18 otherwise, and K_V = 5.33.',
    refs: [{ source: 'rtca-do229', section: 'Appendix J' }, { source: 'icao-annex10', section: 'Appendix B' }, { source: 'faa-waas-pan92', section: '§2.0, text on Figures 2-11 and 2-12 (p. 56): HPL/6.0, VPL/5.33' }],
    status: 'to-confirm',
    value: [6.0, 6.18, 5.33],
    actual: () => [K_H_PA, K_H_NPA, K_V_PA],
    code: 'src/core/receiver.ts',
    todo: 'K factors (RTCA DO-229 / Annex 10 Appendix B)',
  },
  {
    id: 'sbas.raim',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'GPS alone uses RAIM/FDE; its detection thresholds and protection-level factors are illustrative values (false-alarm probability about 10⁻⁵ per epoch, missed-detection probability 10⁻³).',
    refs: [D9849('§4.2'), { source: 'rtca-do229', section: '§2.1 FDE requirements' }],
    status: 'to-confirm',
    value: [7.51, 7.81, 8.02, 8.2, 8.35, 8.49, 8.61, 8.72, 8.83, 8.92],
    unit: '√λ for 1–10 degrees of freedom (non-central χ², Pfa 10⁻⁵, Pmd 10⁻³)',
    actual: () => PBIAS.slice(1),
    code: 'src/core/receiver.ts',
    todo: 'RAIM/FDE thresholds are illustrative',
    note: 'Recomputed in the AI check: the χ² thresholds (19.51 … 41.30) match Pfa 10⁻⁵; the earlier factors (5.4 … 7.2) gave a missed-detection probability of 0.08 to 0.16 and an HPL about 30 % too small. RTCA DO-229 states its false-alert requirement per hour, not per epoch (to confirm).',
  },
  {
    id: 'sbas.mask-angle',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'For SBAS approaches with vertical guidance, the avionics use only satellites at or above 5° elevation; the page applies the same 5° mask in every phase of flight and to the reference stations, as a simplification.',
    refs: [A10('Appendix B 3.5.8.1.2.11'), { source: 'egnos-sol-sdd', section: '§6' }, { source: 'rtca-do229' }],
    status: 'to-confirm',
    value: 5,
    unit: 'degrees',
    actual: () => MASK_DEG,
    code: 'src/core/groundSegment.ts',
    todo: '5° mask angle',
  },
  {
    id: 'sbas.abas-iono-sigma',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'GPS alone: the σ of the broadcast-model ionospheric residual is the larger of T_iono/5 and τ_vert times the obliquity, with τ_vert = 9 m where the pierce point is within 20° of the equator, 4.5 m from 20° to 55° and 6 m beyond (the model Annex 10 gives for an SBAS receiver that is not applying SBAS ionospheric corrections; the page also uses it for GPS alone).',
    refs: [A10('Appendix B 3.5.5.6.3.2'), { source: 'rtca-do229', section: 'Appendix J' }],
    status: 'to-confirm',
    value: [9, 4.5, 6],
    unit: 'm (τ_vert for |φ_pp| ≤ 20°, 20–55°, beyond 55°)',
    actual: () => [tauVertNoSbasM(10), tauVertNoSbasM(-40), tauVertNoSbasM(60)],
    code: 'src/core/iono.ts',
    todo: 'σ of the single-frequency broadcast-model ionospheric residual',
    note: 'The bands are on the geographic latitude of the pierce point (φ_pp), as Annex 10 defines them. The same σ serves L1 SBAS satellites outside the ionospheric grid and the service-area maps.',
  },
  {
    id: 'sbas.dfre',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The DFMC service’s correction bound (DFRE) is modelled with the same bound as UDRE; the DFREI table of ED-259 differs.',
    refs: [{ source: 'eurocae-ed259' }],
    status: 'to-confirm',
    code: 'src/core/sbasWorld.ts',
    todo: 'DFRE is modelled with the same bound as UDRE',
  },
  {
    id: 'sbas.mode-annunciation',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The avionics annunciate the highest level of service the signal supports: LPV, LNAV/VNAV or LNAV. On the final approach segment of an LPV approach, if LPV is lost the receiver shows a flag and stops guidance or reverts to LNAV only, not to LNAV/VNAV.',
    refs: [D9849('§4.3.2.5'), { source: 'faa-waas-ps-2008', section: '§2.3.2' }],
    status: 'sourced',
    code: 'src/core/sbasWorld.ts approachMode',
    note: 'The page works the mode out moment by moment: it does not remember the mode armed before the final approach fix.',
  },
  { id: 'sbas.fas-crc', topic: 'SBAS', scenarios: BOTH, text: 'The final approach segment (FAS) data block defines the LPV final approach, and a CRC protects it.', refs: [D9849('§4.3.2.7')], status: 'sourced', code: 'src/core/approach.ts' },
  {
    id: 'sbas.fas-fields',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The FAS data block’s main fields (operation type, SBAS provider, airport, runway, approach performance designator, route indicator, reference path, landing threshold point, flight path alignment point, threshold crossing height, glide path angle, course width, HAL, VAL), with a typical 105 m course width at the threshold (80–143.75 m allowed).',
    refs: [A10('Appendix B Table B-96'), { source: 'rtca-do229', section: 'Appendix D' }, { source: 'eurocontrol-fasdb' }],
    status: 'to-confirm',
    code: 'src/core/approach.ts',
    todo: 'FAS data block field set',
  },
  {
    id: 'sbas.fas-crc32q',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The FAS data block CRC is a 32-bit CRC (CRC-32Q, polynomial 0x814141AB).',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    value: '0x814141AB',
    actual: () => `0x${(crc32q(new Uint8Array([1])) >>> 0).toString(16).toUpperCase()}`,
    code: 'src/core/approach.ts',
    todo: 'CRC-32Q, polynomial 0x814141AB',
    note: 'The CRC of the single byte 0x01 is the polynomial itself, which is how the binding reads it.',
  },
  { id: 'sbas.channel', topic: 'SBAS', scenarios: BOTH, text: 'Crews can select an SBAS approach by its five-digit channel number.', refs: [D9849('§4.3.2.9')], status: 'sourced', code: 'src/core/approach.ts' },
  {
    id: 'sbas.channel-range',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'SBAS approach channels run from 40 000 to 99 999.',
    refs: [{ source: 'rtca-do229' }],
    status: 'to-confirm',
    value: 1,
    actual: () => (APPROACH_CHANNEL >= 40_000 && APPROACH_CHANNEL <= 99_999 ? 1 : 0),
    code: 'src/core/approach.ts',
    todo: 'SBAS channel number range',
  },
  {
    id: 'sbas.lpv-deviations',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'LPV deviations: lateral full scale is the course width at the threshold and widens at a constant angle measured from the azimuth reference point 305 m beyond the flight path alignment point (an ILS-like splay, about 1.5–2° for a typical runway); vertical full scale is a quarter of the glide path angle.',
    refs: [A10('Appendix B, FAS data block note; Attachment D 7.11.3.1–7.11.3.2, Figure D-15'), { source: 'rtca-do229' }],
    status: 'to-confirm',
    value: 305,
    unit: 'm (azimuth reference point beyond the FPAP)',
    actual: () => GARP_BEYOND_FPAP_M,
    code: 'src/core/approach.ts',
    todo: 'LPV lateral full scale is limited to ±1 NM',
    note: 'The page puts the flight path alignment point at the far end of the runway. Its ±1 NM limit on the lateral full scale is not in Annex 10 or Doc 8168 Vol II and is to be confirmed against RTCA DO-229; it never binds on the final approach shown.',
  },
  {
    id: 'sbas.decision-height',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'The decision height of each scenario’s LPV procedure is illustrative: 250 ft at Bali, 200 ft for the LPV-200 at Nice.',
    refs: [D9849('§4.3.3.3'), { source: 'egnos-sol-sdd', section: '§3.2.1 (APV: LPV minima as low as 250 ft; Category I, VAL 35 m: as low as 200 ft)' }],
    status: 'to-confirm',
    value: [250, 200],
    unit: 'ft (Bali, Nice)',
    actual: () => [SCENARIOS.indonesia.approach.decisionHeightFt, SCENARIOS.essp.approach.decisionHeightFt],
    code: 'src/core/approach.ts',
    todo: 'the LPV decision height is procedure-specific',
  },
  {
    id: 'sbas.two-geos',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'For LNAV/VNAV, LP and LPV the avionics must be able to track two SBAS satellites, so they can switch if one is lost; one satellite with current data is enough to fly the approach.',
    refs: [D9849('§4.3.2.10'), D9849('Appendix G §2.4.1'), { source: 'egnos-sol-sdd', section: '§3.3.1' }],
    status: 'sourced',
    code: 'src/core/sbasWorld.ts',
    note: 'The model keeps LPV with one GEO and loses it when both are lost (after the time-out).',
  },
  { id: 'sbas.abas-fallback', topic: 'SBAS', scenarios: BOTH, text: 'Outside SBAS service, SBAS avionics fall back to ABAS (GPS alone with RAIM) automatically.', refs: [D9849('§4.3.4.3')], status: 'sourced', code: 'src/core/sbasWorld.ts navStatus' },
  { id: 'sbas.no-airport-equipment', topic: 'SBAS', scenarios: BOTH, text: 'SBAS approaches need no dedicated equipment at the airport.', refs: [D9849('§4.3.3.1')], status: 'sourced' },
  {
    id: 'sbas.cat1-200ft',
    topic: 'SBAS',
    scenarios: BOTH,
    text: 'A 35 m VAL supports a 200 ft decision height (LPV-200, equivalent to ILS Category I); in more than 1.76 billion WAAS observations with a VAL of 35 m or less, the largest signal-in-space vertical error was 8.9 m. Annex 10 requires a system-specific safety analysis before a VAL above 10 m is used.',
    refs: [D9849('§4.3.3.3'), A10('Chapter 3 Table 3.7.2.4-1 Note 2; Attachment D 3.3.6')],
    status: 'sourced',
    note: 'The statistic is quoted from Doc 9849 (3rd edition, §4.3.3.3); its section number in the 5th edition is to confirm.',
  },
]
