/**
 * Claims of the SBAS worldwide page (`?view=systems`, src/content/sbasSystems.ts) and of
 * the service-area map of a real day (ESSP-SAS, src/core/serviceMap.ts). One claim per
 * system holds its card's facts; its sources are the providers' and ICAO's public
 * documents, read in October 2026.
 */
import { SBAS_SYSTEMS } from '@/content/sbasSystems'
import { EGNOS_RIMS } from '@/scenarios/essp/rimsNetwork'
import { SERVICE_MAP_GRID_DEG, SERVICE_MAP_STEP_S } from '@/data/servicemap/meta'
import type { Claim } from './types'

const BOTH = ['indonesia', 'essp'] as const
const sys = (id: string) => SBAS_SYSTEMS.find((s) => s.id === id)!
const prns = (id: string) => sys(id).geos.filter((g) => g.prn !== null).map((g) => g.prn!)

export const WORLDWIDE_CLAIMS: readonly Claim[] = [
  {
    id: 'world.waas',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'WAAS (FAA) serves North America: en route, terminal and NPA since 2003, LP since 2011, and LNAV/VNAV, LPV and LPV-200. GEOs PRN 131 (Eutelsat 117 West B, 117°W), 133 (SES-15, 129°W) and 135 (Galaxy 30, 125°W); 38 reference stations; dual-frequency service in development.',
    refs: [{ source: 'faa-waas-pan97', section: 'GEOs, reference stations' }, { source: 'faa-sbas-worldwide', section: 'WAAS' }, { source: 'faa-waas-qfacts' }, { source: 'gps-gov-prn' }],
    status: 'to-confirm',
    value: [131, 133, 135],
    unit: 'PRN',
    actual: () => prns('waas'),
    code: 'src/content/sbasSystems.ts',
    note: 'The 3 master and 6 uplink stations come from a secondary source (Navipedia, 2011) and are to confirm; the years LPV and LPV-200 entered service are not in the sources read.',
  },
  {
    id: 'world.egnos',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'EGNOS serves Europe: the Safety-of-Life service since 2 March 2011 (NPA, APV-I), LPV-200 since 2015. Operational GEOs PRN 136 (SES-5, 5°E) and 121 (Eutelsat 5 West B, 5°W), PRN 123 (ASTRA 5B, 23.5°E) in test; 38 RIMS, two MCCs, two NLES per GEO; ESSP is the service provider under contract to EUSPA.',
    refs: [{ source: 'egnos-sol-sdd', section: '§3.3.1 Table 2, §3.3.2' }, { source: 'egnos-service-notice-33' }, { source: 'egnos-mpr-2026-08' }, { source: 'gps-gov-prn', section: 'PRN 121, 136' }],
    status: 'sourced',
    value: [136, 121, 123],
    unit: 'PRN',
    actual: () => prns('egnos'),
    code: 'src/content/sbasSystems.ts',
  },
  {
    id: 'world.msas',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'MSAS (JCAB) serves Japan only: en route to NPA since 2007; LP and LPV (LPV to 250 ft, VAL 50 m) introduced in phases, at 25 airports by January 2026; LPV-200 planned for 2027. GEOs QZS-3 (PRN 137, 127°E) and QZS-6 (PRN 129, 90.5°E), both operational, QZS-6 since October 2025; QZS-7 (PRN 139) awaiting launch.',
    refs: [{ source: 'icao-apac-itf8-japan', section: '§1, §2, §5' }, { source: 'jcab-msas-2021', section: 'ground segment counts' }, { source: 'gps-gov-prn' }],
    status: 'sourced',
    value: [137, 129, 139],
    unit: 'PRN',
    actual: () => prns('msas'),
    code: 'src/content/sbasSystems.ts',
    note: 'Station counts (13 monitor, 2 master, 3 uplink) are of 2021; MSAS v3 (2025) changed the network. The gps.gov PRN list gives QZS-7 (PRN 139) a slot at 175°W; the card shows no position until it is launched.',
  },
  {
    id: 'world.gagan',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'GAGAN (AAI, certified by DGCA India): RNP 0.1 en route over the Indian FIRs since 2013 and, since 2015, APV-I (VAL 50 m, LPV to 250 ft) 99 % of the time over 76 % of the Indian landmass; three GEOs broadcast its messages, GSAT-8 (PRN 127, 55°E), GSAT-10 (PRN 128, 83°E) and GSAT-15 (PRN 132, 93.5°E); 15 reference stations, 2 master and 3 uplink stations.',
    refs: [{ source: 'icao-apac-itf7-india' }, { source: 'icao-apac-sbas-guidance-2025', section: '§2.4 (GEOs), §2.4.1 and §2.5 (e-AIP India ENR 4.3: APV-I area)' }, { source: 'aai-gagan-2025' }, { source: 'gps-gov-prn' }],
    status: 'to-confirm',
    value: [127, 128, 132],
    unit: 'PRN',
    actual: () => prns('gagan'),
    code: 'src/content/sbasSystems.ts',
    note: 'The ICAO APAC guidance says the uplink sends the messages to all three GEOs and they broadcast them; it does not say whether one is a standby. e-AIP India ENR 4.3 makes the service subject to at least one GAGAN GEO. The APV-I figures exclude solar-storm periods (the guidance, §2.4.1). 250 ft is the lowest LPV minimum an APV-I service (VAL 50 m) supports, as EGNOS SoL SDD v3.6 §3.2.1 states it for EGNOS; no GAGAN source read states 250 ft itself (to confirm).',
  },
  {
    id: 'world.kass',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'KASS (MOLIT) has offered an APV-I Safety-of-Life service in the Incheon FIR since 28 December 2023, with a second GEO in operation since 18 February 2026: MEASAT-3D (PRN 134, 91.5°E) and KOREASAT 6A (PRN 142, 116°E). Its ground segment: 7 reference stations, 2 processing stations, 2 control stations and 3 uplink stations at 2 sites.',
    refs: [{ source: 'icao-apac-itf8-korea', section: '§2.1–2.4' }, { source: 'gps-gov-prn' }],
    status: 'sourced',
    value: [134, 142],
    unit: 'PRN',
    actual: () => prns('kass'),
    code: 'src/content/sbasSystems.ts',
  },
  {
    id: 'world.southpan',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'SouthPAN (Geoscience Australia with Toitū Te Whenua LINZ) has broadcast open services since September 2022, not for aviation, on PRN 122 (the Inmarsat-4 F2 payload, 143.5°E), from 2 uplinks (Uralla, Australia; Awarua, New Zealand); Safety-of-Life L1 SBAS services for aviation are planned from 2028 (indicative).',
    refs: [{ source: 'southpan-sdd', section: '§4.1 space segment' }, { source: 'icao-apac-itf8-report' }, { source: 'gps-gov-prn', section: 'PRN 122' }],
    status: 'sourced',
    value: 2028,
    unit: 'planned year of aviation services',
    actual: () => sys('southpan').services[0].year!,
    code: 'src/content/sbasSystems.ts',
  },
  {
    id: 'world.bdsbas',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'BDSBAS (China) has broadcast single-frequency and DFMC test services since 2020 and is in testing and certification, not yet for civil aviation; LPV procedures are expected around 2029. GEOs PRN 130 (140°E), 143 (110.5°E) and 144 (80°E); in 2021, 30 monitoring stations, 2 data processing centres, 1 operation control centre and 3 uplink stations.',
    refs: [{ source: 'navigation-bdsbas-2021', section: '§2.1.2, Table 3' }, { source: 'icao-apac-itf8-report' }, { source: 'faa-sbas-worldwide', section: 'BDSBAS' }, { source: 'gps-gov-prn', section: 'PRN 130, 143, 144' }],
    status: 'sourced',
    value: 2029,
    unit: 'expected year of LPV',
    actual: () => sys('bdsbas').services[0].year!,
    code: 'src/content/sbasSystems.ts',
    note: 'The ITF/8 report is a draft. No official source read names the BDSBAS operator.',
  },
  {
    id: 'world.sdcm',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'SDCM (Russia) is pre-operational: it passed preliminary certification tests for APV-I and APV-II (Roscosmos, 2024) and is not certified for civil aviation; GEOs Luch-5B (PRN 125, 16°W) and Luch-5V (PRN 140, 95°E).',
    refs: [{ source: 'roscosmos-icg18' }, { source: 'faa-sbas-worldwide', section: 'SDCM' }, { source: 'gps-gov-prn' }],
    status: 'sourced',
    code: 'src/content/sbasSystems.ts',
  },
  {
    id: 'world.anga',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'ASECNA’s A-SBAS (ANGA) has broadcast a demonstration signal since September 2020 that certified receivers may not use (Message Type 0); ASECNA expects airlines to benefit from its services from 2028/29.',
    refs: [{ source: 'icao-a41-wp298' }, { source: 'canso-asecna-2020', section: 'Message Type 0' }, { source: 'asecna-anga-2024' }],
    status: 'sourced',
    code: 'src/content/sbasSystems.ts',
  },
  {
    id: 'world.paksbas',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'Pak-SBAS (SUPARCO) was commissioned in 2024 on PakSat-MM1 (PRN 145, 38.2°E) and is available for testing; aviation implementation is being prepared.',
    refs: [{ source: 'icao-apac-itf8-report' }, { source: 'gps-gov-prn' }],
    status: 'to-confirm',
    code: 'src/content/sbasSystems.ts',
    note: 'Known from the ITF/8 report summary only; Pakistan’s own paper was not read.',
  },
  {
    id: 'world.studies',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'SACCSA, an ICAO regional study for the Caribbean, Central and South America, closed in 2015 without building a system; the UK SBAS test-bed broadcast a test signal on PRN 158 under ESA NAVISP and offers no aviation service.',
    refs: [{ source: 'icao-sam-saccsa-2015' }, { source: 'esa-navisp-uksbas' }],
    status: 'sourced',
    code: 'src/content/sbasSystems.ts',
  },
  {
    id: 'world.areas',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'The service areas on the world map are rough outlines drawn from each provider’s wording (for example "North America", "the Incheon FIR"), not official coverage maps.',
    refs: [{ source: 'faa-sbas-worldwide' }, { source: 'egnos-sol-sdd', section: 'service area' }],
    status: 'to-confirm',
    code: 'src/content/sbasSystems.ts',
    note: 'Illustrative by design; the page labels them approximate.',
  },
  {
    id: 'world.architecture',
    topic: 'SBAS worldwide',
    scenarios: BOTH,
    text: 'Every SBAS follows the same chain: reference stations measure the satellites, master stations compute corrections and integrity, uplink stations send them to GEO satellites, which broadcast 250-bit messages every second on L1; for LPV-200 the system must warn of a fault within 6 s, against alert limits of 40 m horizontal and 35 m vertical.',
    refs: [{ source: 'icao-annex10', section: 'Table 3.7.2.4-1' }, { source: 'egnos-sol-sdd', section: '§3.3, Table 7' }, { source: 'faa-waas-pan97', section: 'Table 1-1' }],
    status: 'sourced',
    code: 'src/content/sbasSystems.ts SBAS_CHAIN',
  },
  {
    id: 'servicemap.real-day',
    topic: 'Real signal',
    scenarios: ['essp'],
    text: 'The service-area map uses real data of 30 September 2026, a geomagnetically quiet day: the IGS broadcast ephemeris (real GPS orbits and clocks) and the observations of 15 EUREF Permanent Network stations, from the BKG GNSS Data Center.',
    refs: [{ source: 'bkg-gdc' }, { source: 'euref-epn' }, { source: 'gfz-kp', section: 'Kp, 30 September 2026' }],
    status: 'sourced',
    code: 'scripts/data/fetch-bkg.mjs',
  },
  {
    id: 'servicemap.method',
    topic: 'Real signal',
    scenarios: ['essp'],
    text: 'At each point of a 2° grid, every 10 minutes, the map computes an SBAS receiver’s protection levels from the real satellite geometry (the same receiver code as the journey) and compares them with the alert limits; at the stations it also computes a GPS-alone fix from their real pseudoranges (broadcast orbits and clocks, Klobuchar ionosphere, tropospheric model) and its error against the station’s position in its RINEX file (the marker plus the antenna height). That position is accurate to the metre at some stations: the Italian station VLFR shows a steady vertical offset of about 1.9 m.',
    refs: [{ source: 'is-gps-200', section: '§20.3.3.4.3, §20.3.3.5.2.5' }, { source: 'rtca-do229', section: 'Appendix J' }],
    status: 'sourced',
    value: [2, 600],
    unit: '° (grid spacing), s (time step)',
    actual: () => [SERVICE_MAP_GRID_DEG, SERVICE_MAP_STEP_S],
    code: 'src/core/serviceMap.ts',
    note: 'The values are bound to src/data/servicemap/meta.ts, which the claims test checks against the shipped map.',
  },
  {
    id: 'servicemap.rims-network',
    topic: 'Real signal',
    scenarios: ['essp'],
    text: 'Until real EGNOS messages of the day are loaded, the map models the EGNOS corrections on the real geometry with the 32 RIMS sites ESSP names in its August 2026 performance report, placed at their cities; the full network has 38.',
    refs: [{ source: 'egnos-mpr-2026-08', section: 'Table 7' }, { source: 'egnos-sol-sdd', section: '§3.3.2.1' }],
    status: 'to-confirm',
    value: 32,
    unit: 'RIMS sites',
    actual: () => EGNOS_RIMS.length,
    code: 'src/scenarios/essp/rimsNetwork.ts',
    note: 'The modelled UDRE and GIVE are the page’s own model, labelled "modelled" on screen; they are not EGNOS’s broadcast values.',
  },
  {
    id: 'servicemap.egnos-real',
    topic: 'Real signal',
    scenarios: ['essp'],
    text: 'With real EGNOS messages (EMS files, for example from EDAS), the map skips any message whose checksum (CRC) fails and takes the UDREIs (Message Types 2–6 and 24) and the ionospheric grid from the broadcast. It interpolates the grid in 5° cells (5° × 10° between 60° and 75° of latitude, where the grid points are 10° apart), over three grid points when the fourth is missing or not monitored. It does not yet fall back to 10° cells or use the polar grid points beyond 75°, and it does not apply the Message Type 28 covariance (δUDRE), the degradation terms of Message Types 7 and 10 or the long-term corrections. The map shipped today uses modelled corrections.',
    refs: [{ source: 'rtca-do229', section: 'Appendix A' }, { source: 'esa-ems' }],
    status: 'to-confirm',
    code: 'src/core/serviceMap.ts groundFromDecoder',
  },
]
